-- 카탈로그 한글 표기 (scripts/translate-catalog-names.mjs — 사전 기반 직접 번역)

ALTER TABLE whisky_note.catalog ADD COLUMN name_ko text;

-- 시드 데이터 오타 수정
UPDATE whisky_note.catalog SET name = 'Auchentoshan 12 Year Old' WHERE name = 'Auchentoship 12 Year Old';

UPDATE whisky_note.catalog SET name_ko = '글렌피딕 12년' WHERE name = 'Glenfiddich 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 15년 솔레라 리저브' WHERE name = 'Glenfiddich 15 Year Old Solera Reserve';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 18년' WHERE name = 'Glenfiddich 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 21년 리제르바 럼 캐스크 피니시' WHERE name = 'Glenfiddich 21 Year Old Reserva Rum Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 30년' WHERE name = 'Glenfiddich 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 12년 솔레라' WHERE name = 'Glenfiddich 12 Year Old Solera';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 18년 레어 오크' WHERE name = 'Glenfiddich 18 Year Old Rare Oak';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 프로젝트 XX' WHERE name = 'Glenfiddich Project XX';
UPDATE whisky_note.catalog SET name_ko = '글렌피딕 50년' WHERE name = 'Glenfiddich 50 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 더블우드 12년' WHERE name = 'The Balvenie DoubleWood 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 더블우드 14년' WHERE name = 'The Balvenie DoubleWood 14 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 더블우드 21년' WHERE name = 'The Balvenie DoubleWood 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 캐리비안 캐스크 14년' WHERE name = 'The Balvenie Caribbean Cask 14 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 포트우드 21년' WHERE name = 'The Balvenie PortWood 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 툰 1509 배치 6' WHERE name = 'The Balvenie Tun 1509 Batch 6';
UPDATE whisky_note.catalog SET name_ko = '발베니 30년' WHERE name = 'The Balvenie 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 35년' WHERE name = 'The Balvenie 35 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발베니 40년' WHERE name = 'The Balvenie 40 Year Old';
UPDATE whisky_note.catalog SET name_ko = '키닌비 12년' WHERE name = 'Kininvie 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '키닌비 15년' WHERE name = 'Kininvie 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '키닌비 18년' WHERE name = 'Kininvie 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '키닌비 21년' WHERE name = 'Kininvie 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '키닌비 30년' WHERE name = 'Kininvie 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '키닌비 12년 셰리 캐스크 피니시' WHERE name = 'Kininvie 12 Year Old Sherry Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '키닌비 12년 포트 캐스크 피니시' WHERE name = 'Kininvie 12 Year Old Port Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '키닌비 12년 캐스크 스트렝스' WHERE name = 'Kininvie 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '키닌비 12년 싱글 캐스크' WHERE name = 'Kininvie 12 Year Old Single Cask';
UPDATE whisky_note.catalog SET name_ko = '맥캘란 셰리 오크 12년' WHERE name = 'The Macallan Sherry Oak 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '맥캘란 더블 캐스크 18년' WHERE name = 'The Macallan Double Cask 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '맥캘란 레어 캐스크 블랙 2022' WHERE name = 'The Macallan Rare Cask Black 2022';
UPDATE whisky_note.catalog SET name_ko = '맥캘란 에디션 No. 6 – 레드 컬렉션' WHERE name = 'The Macallan Edition No. 6 – The Red Collection';
UPDATE whisky_note.catalog SET name_ko = '아벨라워 12년' WHERE name = 'Aberlour 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아벨라워 아부나흐' WHERE name = 'Aberlour A''Bunadh';
UPDATE whisky_note.catalog SET name_ko = '아벨라워 21년' WHERE name = 'Aberlour 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아벨라워 30년' WHERE name = 'Aberlour 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '카듀 12년' WHERE name = 'Cardhu 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '카듀 골드 리저브' WHERE name = 'Cardhu Gold Reserve';
UPDATE whisky_note.catalog SET name_ko = '카듀 18년' WHERE name = 'Cardhu 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '카듀 리미티드 에디션 2021 – 글렌리벳 컬래버레이션' WHERE name = 'Cardhu Limited Edition 2021 – The Glenlivet Collaboration';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 12년' WHERE name = 'The Glenlivet 12 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 15년' WHERE name = 'The Glenlivet 15 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 18년' WHERE name = 'The Glenlivet 18 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 21년' WHERE name = 'The Glenlivet 21 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 아카이브 21년' WHERE name = 'The Glenlivet Archive 21 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 파운더스 리저브' WHERE name = 'The Glenlivet Founder’s Reserve';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 나두라' WHERE name = 'The Glenlivet Nadurra';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 30년' WHERE name = 'The Glenlivet 30 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌리벳 12년 캐스크 스트렝스' WHERE name = 'The Glenlivet 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '글렌 그란트 10년' WHERE name = 'Glen Grant 10 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌 그란트 12년' WHERE name = 'Glen Grant 12 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌 그란트 15년' WHERE name = 'Glen Grant 15 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌 그란트 18년' WHERE name = 'Glen Grant 18 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌 그란트 21년' WHERE name = 'Glen Grant 21 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌 그란트 프라이빗 리저브' WHERE name = 'Glen Grant Private Reserve';
UPDATE whisky_note.catalog SET name_ko = '롱몬 12년' WHERE name = 'Longmorn 12 Year';
UPDATE whisky_note.catalog SET name_ko = '롱몬 18년' WHERE name = 'Longmorn 18 Year';
UPDATE whisky_note.catalog SET name_ko = '롱몬 21년' WHERE name = 'Longmorn 21 Year';
UPDATE whisky_note.catalog SET name_ko = '롱몬 25년' WHERE name = 'Longmorn 25 Year';
UPDATE whisky_note.catalog SET name_ko = '롱몬 12년 캐스크 스트렝스' WHERE name = 'Longmorn 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 12년' WHERE name = 'Glenfarclas 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 15년' WHERE name = 'Glenfarclas 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 18년' WHERE name = 'Glenfarclas 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 21년' WHERE name = 'Glenfarclas 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 25년' WHERE name = 'Glenfarclas 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 30년' WHERE name = 'Glenfarclas 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 40년' WHERE name = 'Glenfarclas 40 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌파클라스 1990 (NAS)' WHERE name = 'Glenfarclas 1990 (NAS)';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 12년' WHERE name = 'Craigellachie 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 13년' WHERE name = 'Craigellachie 13 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 14년' WHERE name = 'Craigellachie 14 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 16년' WHERE name = 'Craigellachie 16 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 19년' WHERE name = 'Craigellachie 19 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 25년' WHERE name = 'Craigellachie 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 30년' WHERE name = 'Craigellachie 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라겔라키 1995 (NAS)' WHERE name = 'Craigellachie 1995 (NAS)';
UPDATE whisky_note.catalog SET name_ko = '올트모어 12년' WHERE name = 'Aultmore 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올트모어 15년' WHERE name = 'Aultmore 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올트모어 18년' WHERE name = 'Aultmore 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올트모어 21년' WHERE name = 'Aultmore 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올트모어 25년' WHERE name = 'Aultmore 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올트모어 30년' WHERE name = 'Aultmore 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올트모어 1990 (NAS)' WHERE name = 'Aultmore 1990 (NAS)';
UPDATE whisky_note.catalog SET name_ko = '모틀락 12년' WHERE name = 'Mortlach 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '모틀락 16년' WHERE name = 'Mortlach 16 Year Old';
UPDATE whisky_note.catalog SET name_ko = '모틀락 21년' WHERE name = 'Mortlach 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '모틀락 25년' WHERE name = 'Mortlach 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '모틀락 30년' WHERE name = 'Mortlach 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '모틀락 12년 셰리 캐스크' WHERE name = 'Mortlach 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '모틀락 12년 버번 캐스크' WHERE name = 'Mortlach 12 Year Old Bourbon Cask';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 더프타운 12년' WHERE name = 'The Singleton of Dufftown 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 더프타운 15년' WHERE name = 'The Singleton of Dufftown 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 더프타운 18년' WHERE name = 'The Singleton of Dufftown 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 더프타운 12년 셰리 캐스크' WHERE name = 'The Singleton of Dufftown 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 더프타운 12년 포트 캐스크' WHERE name = 'The Singleton of Dufftown 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌둘란 12년' WHERE name = 'Glendullan 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌둘란 15년' WHERE name = 'Glendullan 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌둘란 18년' WHERE name = 'Glendullan 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌둘란 12년 셰리 캐스크' WHERE name = 'Glendullan 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌둘란 12년 포트 캐스크' WHERE name = 'Glendullan 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌둘란 12년 럼 캐스크' WHERE name = 'Glendullan 12 Year Old Rum Cask';
UPDATE whisky_note.catalog SET name_ko = '벤리악 10년' WHERE name = 'BenRiach 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '벤리악 12년' WHERE name = 'BenRiach 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '벤리악 21년' WHERE name = 'BenRiach 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '벤리악 25년' WHERE name = 'BenRiach 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '벤리악 피트 스모크' WHERE name = 'BenRiach Peat Smoke';
UPDATE whisky_note.catalog SET name_ko = '벤리악 12년 셰리 캐스크' WHERE name = 'BenRiach 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '벤리악 12년 포트 캐스크' WHERE name = 'BenRiach 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌 모레이 10년' WHERE name = 'Glen Moray 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 모레이 12년' WHERE name = 'Glen Moray 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 모레이 15년' WHERE name = 'Glen Moray 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 모레이 18년' WHERE name = 'Glen Moray 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 모레이 21년' WHERE name = 'Glen Moray 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 모레이 30년' WHERE name = 'Glen Moray 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 모레이 레거시' WHERE name = 'Glen Moray Legacy';
UPDATE whisky_note.catalog SET name_ko = '스페이번 10년' WHERE name = 'Speyburn 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스페이번 12년' WHERE name = 'Speyburn 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스페이번 15년' WHERE name = 'Speyburn 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스페이번 18년' WHERE name = 'Speyburn 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스페이번 21년' WHERE name = 'Speyburn 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스페이번 25년' WHERE name = 'Speyburn 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스페이번 12년 셰리 캐스크' WHERE name = 'Speyburn 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '스페이번 12년 포트 캐스크' WHERE name = 'Speyburn 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '벤로막 10년' WHERE name = 'Benromach 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '벤로막 12년' WHERE name = 'Benromach 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '벤로막 피트 스모크' WHERE name = 'Benromach Peat Smoke';
UPDATE whisky_note.catalog SET name_ko = '벤로막 배치 1' WHERE name = 'Benromach Batch 1';
UPDATE whisky_note.catalog SET name_ko = '벤로막 25년' WHERE name = 'Benromach 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌로시스 12년' WHERE name = 'The Glenrothes 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌로시스 18년' WHERE name = 'The Glenrothes 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌로시스 21년' WHERE name = 'The Glenrothes 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌로시스 25년' WHERE name = 'The Glenrothes 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌로시스 셀렉트' WHERE name = 'The Glenrothes Select';
UPDATE whisky_note.catalog SET name_ko = '글렌 엘긴 12년' WHERE name = 'Glen Elgin 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 엘긴 15년' WHERE name = 'Glen Elgin 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 엘긴 18년' WHERE name = 'Glen Elgin 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 엘긴 21년' WHERE name = 'Glen Elgin 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 엘긴 12년 셰리 캐스크' WHERE name = 'Glen Elgin 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌 엘긴 12년 포트 캐스크' WHERE name = 'Glen Elgin 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '스트라스아일라 12년' WHERE name = 'Strathisla 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스트라스아일라 18년' WHERE name = 'Strathisla 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스트라스아일라 25년' WHERE name = 'Strathisla 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스트라스아일라 12년 캐스크 스트렝스' WHERE name = 'Strathisla 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '스트라스아일라 12년 셰리 캐스크' WHERE name = 'Strathisla 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '스트라스아일라 12년 포트 캐스크' WHERE name = 'Strathisla 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '탐듀 10년' WHERE name = 'Tamdhu 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '탐듀 12년' WHERE name = 'Tamdhu 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '탐듀 15년' WHERE name = 'Tamdhu 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '탐듀 12년 캐스크 스트렝스' WHERE name = 'Tamdhu 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '탐듀 12년 셰리 캐스크' WHERE name = 'Tamdhu 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '탐듀 10년 포트 캐스크' WHERE name = 'Tamdhu 10 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '노칸두 12년' WHERE name = 'Knockando 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '노칸두 15년' WHERE name = 'Knockando 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '노칸두 18년' WHERE name = 'Knockando 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '노칸두 12년 캐스크 스트렝스' WHERE name = 'Knockando 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '노칸두 12년 셰리 캐스크' WHERE name = 'Knockando 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '노칸두 12년 포트 캐스크' WHERE name = 'Knockando 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '링크우드 12년' WHERE name = 'Linkwood 12 Year';
UPDATE whisky_note.catalog SET name_ko = '링크우드 18년' WHERE name = 'Linkwood 18 Year';
UPDATE whisky_note.catalog SET name_ko = '링크우드 12년 캐스크 스트렝스' WHERE name = 'Linkwood 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '링크우드 12년 셰리 캐스크' WHERE name = 'Linkwood 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '토모어 12년' WHERE name = 'Tormore 12 Year';
UPDATE whisky_note.catalog SET name_ko = '토모어 14년' WHERE name = 'Tormore 14 Year';
UPDATE whisky_note.catalog SET name_ko = '토모어 12년 캐스크 스트렝스' WHERE name = 'Tormore 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '토모어 12년 셰리 캐스크' WHERE name = 'Tormore 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌토커스 12년' WHERE name = 'Glentauchers 12 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌토커스 18년' WHERE name = 'Glentauchers 18 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌토커스 12년 셰리 캐스크' WHERE name = 'Glentauchers 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌토커스 12년 캐스크 스트렝스' WHERE name = 'Glentauchers 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '탐나불린 10년' WHERE name = 'Tamnavulin 10 Year';
UPDATE whisky_note.catalog SET name_ko = '탐나불린 12년' WHERE name = 'Tamnavulin 12 Year';
UPDATE whisky_note.catalog SET name_ko = '탐나불린 12년 셰리 캐스크' WHERE name = 'Tamnavulin 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '탐나불린 12년 캐스크 스트렝스' WHERE name = 'Tamnavulin 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '크라간모어 12년' WHERE name = 'Cragganmore 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라간모어 15년' WHERE name = 'Cragganmore 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라간모어 18년' WHERE name = 'Cragganmore 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라간모어 25년' WHERE name = 'Cragganmore 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '크라간모어 캐스크 스트렝스' WHERE name = 'Cragganmore Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '다일유인 12년' WHERE name = 'Dailuaine 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '다일유인 15년' WHERE name = 'Dailuaine 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '다일유인 18년' WHERE name = 'Dailuaine 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '다일유인 21년' WHERE name = 'Dailuaine 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '다일유인 포트 우드 피니시' WHERE name = 'Dailuaine Port Wood Finish';
UPDATE whisky_note.catalog SET name_ko = '인치가워 12년' WHERE name = 'Inchgower 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '인치가워 15년' WHERE name = 'Inchgower 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '인치가워 18년' WHERE name = 'Inchgower 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '인치가워 21년' WHERE name = 'Inchgower 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '인치가워 캐스크 스트렝스' WHERE name = 'Inchgower Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '발린달록 12년' WHERE name = 'Ballindalloch 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발린달록 15년' WHERE name = 'Ballindalloch 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발린달록 18년' WHERE name = 'Ballindalloch 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발린달록 21년' WHERE name = 'Ballindalloch 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발린달록 캐스크 스트렝스' WHERE name = 'Ballindalloch Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '글렌모렌지 오리지널 10년' WHERE name = 'Glenmorangie Original 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌모렌지 넥타 도르' WHERE name = 'Glenmorangie Nectar d''Or';
UPDATE whisky_note.catalog SET name_ko = '글렌모렌지 라산타 12년' WHERE name = 'Glenmorangie Lasanta 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌모렌지 시그넷' WHERE name = 'Glenmorangie Signet';
UPDATE whisky_note.catalog SET name_ko = '글렌모렌지 18년' WHERE name = 'Glenmorangie 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '달모어 12년' WHERE name = 'The Dalmore 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '달모어 15년' WHERE name = 'The Dalmore 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '달모어 18년' WHERE name = 'The Dalmore 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '달모어 킹 알렉산더 3세' WHERE name = 'The Dalmore King Alexander III';
UPDATE whisky_note.catalog SET name_ko = '달모어 시가 몰트' WHERE name = 'The Dalmore Cigar Malt';
UPDATE whisky_note.catalog SET name_ko = '글렌드로낙 12년 오리지널' WHERE name = 'The GlenDronach 12 Year Old Original';
UPDATE whisky_note.catalog SET name_ko = '글렌드로낙 15년 리바이벌' WHERE name = 'The GlenDronach 15 Year Old Revival';
UPDATE whisky_note.catalog SET name_ko = '글렌드로낙 18년 알라디스' WHERE name = 'The GlenDronach 18 Year Old Allardice';
UPDATE whisky_note.catalog SET name_ko = '글렌드로낙 21년 팔러먼트' WHERE name = 'The GlenDronach 21 Year Old Parliament';
UPDATE whisky_note.catalog SET name_ko = '글렌드로낙 12년 캐스크 스트렝스' WHERE name = 'The GlenDronach 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '오반 14년' WHERE name = 'Oban 14 Year Old';
UPDATE whisky_note.catalog SET name_ko = '오반 18년' WHERE name = 'Oban 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '오반 8년' WHERE name = 'Oban 8 Year Old';
UPDATE whisky_note.catalog SET name_ko = '오반 리틀 베이' WHERE name = 'Oban Little Bay';
UPDATE whisky_note.catalog SET name_ko = '오반 디스틸러스 에디션' WHERE name = 'Oban Distillers Edition';
UPDATE whisky_note.catalog SET name_ko = '클라이넬리시 14년' WHERE name = 'Clynelish 14 Year Old';
UPDATE whisky_note.catalog SET name_ko = '클라이넬리시 12년' WHERE name = 'Clynelish 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '클라이넬리시 18년' WHERE name = 'Clynelish 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '클라이넬리시 25년' WHERE name = 'Clynelish 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '클라이넬리시 30년' WHERE name = 'Clynelish 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올드 풀트니 12년' WHERE name = 'Old Pulteney 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올드 풀트니 12년 포트 우드 피니시' WHERE name = 'Old Pulteney 12 Year Old Port Wood Finish';
UPDATE whisky_note.catalog SET name_ko = '올드 풀트니 12년 셰리 우드 피니시' WHERE name = 'Old Pulteney 12 Year Old Sherry Wood Finish';
UPDATE whisky_note.catalog SET name_ko = '올드 풀트니 18년' WHERE name = 'Old Pulteney 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올드 풀트니 21년' WHERE name = 'Old Pulteney 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '달위니 12년' WHERE name = 'Dalwhinnie 12 Year';
UPDATE whisky_note.catalog SET name_ko = '달위니 15년' WHERE name = 'Dalwhinnie 15 Year';
UPDATE whisky_note.catalog SET name_ko = '달위니 18년' WHERE name = 'Dalwhinnie 18 Year';
UPDATE whisky_note.catalog SET name_ko = '달위니 25년' WHERE name = 'Dalwhinnie 25 Year';
UPDATE whisky_note.catalog SET name_ko = '달위니 30년' WHERE name = 'Dalwhinnie 30 Year';
UPDATE whisky_note.catalog SET name_ko = '토마틴 12년' WHERE name = 'Tomatin 12 Year';
UPDATE whisky_note.catalog SET name_ko = '토마틴 12년 셰리 캐스크' WHERE name = 'Tomatin 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '토마틴 12년 포트 캐스크' WHERE name = 'Tomatin 12 Year Port Cask';
UPDATE whisky_note.catalog SET name_ko = '토마틴 18년' WHERE name = 'Tomatin 18 Year';
UPDATE whisky_note.catalog SET name_ko = '토마틴 21년' WHERE name = 'Tomatin 21 Year';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 글렌 오드 12년' WHERE name = 'The Singleton Glen Ord 12 Year';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 글렌 오드 12년 셰리 캐스크' WHERE name = 'The Singleton Glen Ord 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 글렌 오드 15년' WHERE name = 'The Singleton Glen Ord 15 Year';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 글렌 오드 18년' WHERE name = 'The Singleton Glen Ord 18 Year';
UPDATE whisky_note.catalog SET name_ko = '싱글턴 글렌 오드 21년' WHERE name = 'The Singleton Glen Ord 21 Year';
UPDATE whisky_note.catalog SET name_ko = '애버펠디 12년' WHERE name = 'Aberfeldy 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '애버펠디 21년' WHERE name = 'Aberfeldy 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '애버펠디 10년' WHERE name = 'Aberfeldy 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '애버펠디 30년' WHERE name = 'Aberfeldy 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '애버펠디 1995 NAS' WHERE name = 'Aberfeldy 1995 NAS';
UPDATE whisky_note.catalog SET name_ko = '에드라두어 12년' WHERE name = 'Edradour 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '에드라두어 15년' WHERE name = 'Edradour 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '에드라두어 18년' WHERE name = 'Edradour 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '에드라두어 25년' WHERE name = 'Edradour 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '에드라두어 1999 NAS' WHERE name = 'Edradour 1999 NAS';
UPDATE whisky_note.catalog SET name_ko = '블레어 아솔 12년' WHERE name = 'Blair Athol 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블레어 아솔 15년' WHERE name = 'Blair Athol 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블레어 아솔 18년' WHERE name = 'Blair Athol 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블레어 아솔 21년' WHERE name = 'Blair Athol 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블레어 아솔 1995 NAS' WHERE name = 'Blair Athol 1995 NAS';
UPDATE whisky_note.catalog SET name_ko = '글렌고인 10년' WHERE name = 'Glengoyne 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌고인 12년 셰리 캐스크' WHERE name = 'Glengoyne 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌고인 21년' WHERE name = 'Glengoyne 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌고인 25년' WHERE name = 'Glengoyne 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '딘스톤 12년' WHERE name = 'Deanston 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '딘스톤 18년' WHERE name = 'Deanston 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '딘스톤 21년 셰리 캐스크' WHERE name = 'Deanston 21 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '딘스톤 30년' WHERE name = 'Deanston 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '툴리바딘 12년' WHERE name = 'Tullibardine 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '툴리바딘 18년' WHERE name = 'Tullibardine 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '툴리바딘 21년 셰리 캐스크' WHERE name = 'Tullibardine 21 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '툴리바딘 30년' WHERE name = 'Tullibardine 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로열 로크나가 12년' WHERE name = 'Royal Lochnagar 12 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 로크나가 18년' WHERE name = 'Royal Lochnagar 18 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 로크나가 21년' WHERE name = 'Royal Lochnagar 21 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 로크나가 12년 셰리 캐스크' WHERE name = 'Royal Lochnagar 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '페터케언 12년' WHERE name = 'Fettercairn 12 Year';
UPDATE whisky_note.catalog SET name_ko = '페터케언 21년' WHERE name = 'Fettercairn 21 Year';
UPDATE whisky_note.catalog SET name_ko = '페터케언 12년 셰리 캐스크' WHERE name = 'Fettercairn 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '페터케언 12년 포트 캐스크' WHERE name = 'Fettercairn 12 Year Port Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌카담 10년' WHERE name = 'Glencadam 10 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌카담 12년' WHERE name = 'Glencadam 12 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌카담 18년' WHERE name = 'Glencadam 18 Year';
UPDATE whisky_note.catalog SET name_ko = '글렌카담 12년 셰리 캐스크' WHERE name = 'Glencadam 12 Year Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌카담 12년 포트 캐스크' WHERE name = 'Glencadam 12 Year Port Cask';
UPDATE whisky_note.catalog SET name_ko = '안녹 12년' WHERE name = 'anCnoc 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '안녹 14년' WHERE name = 'anCnoc 14 Year Old';
UPDATE whisky_note.catalog SET name_ko = '안녹 18년' WHERE name = 'anCnoc 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '안녹 피트하트' WHERE name = 'anCnoc Peatheart';
UPDATE whisky_note.catalog SET name_ko = '발블레어 12년' WHERE name = 'Balblair 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발블레어 15년' WHERE name = 'Balblair 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발블레어 21년' WHERE name = 'Balblair 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발블레어 30년' WHERE name = 'Balblair 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '발블레어 1990 빈티지' WHERE name = 'Balblair 1990 Vintage';
UPDATE whisky_note.catalog SET name_ko = '글렌 기어리 12년' WHERE name = 'Glen Garioch 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 기어리 18년' WHERE name = 'Glen Garioch 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 기어리 21년' WHERE name = 'Glen Garioch 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 기어리 1990 빈티지' WHERE name = 'Glen Garioch 1990 Vintage';
UPDATE whisky_note.catalog SET name_ko = '글렌 기어리 30년' WHERE name = 'Glen Garioch 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아드모어 레거시 12년' WHERE name = 'Ardmore Legacy 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아드모어 트래디셔널 12년' WHERE name = 'Ardmore Traditional 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아드모어 10년' WHERE name = 'Ardmore 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아드모어 18년' WHERE name = 'Ardmore 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아드모어 25년' WHERE name = 'Ardmore 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로크 로몬드 오리지널' WHERE name = 'Loch Lomond Original';
UPDATE whisky_note.catalog SET name_ko = '로크 로몬드 12년' WHERE name = 'Loch Lomond 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로크 로몬드 18년' WHERE name = 'Loch Lomond 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로크 로몬드 트리플 우드' WHERE name = 'Loch Lomond Triple Wood';
UPDATE whisky_note.catalog SET name_ko = '로크 로몬드 12년 셰리 캐스크' WHERE name = 'Loch Lomond 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '울프번 12년' WHERE name = 'Wolfburn 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '울프번 16년' WHERE name = 'Wolfburn 16 Year Old';
UPDATE whisky_note.catalog SET name_ko = '울프번 12년 셰리 캐스크' WHERE name = 'Wolfburn 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '울프번 12년 캐스크 스트렝스' WHERE name = 'Wolfburn 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '글렌글라사 12년' WHERE name = 'Glenglassaugh 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌글라사 15년' WHERE name = 'Glenglassaugh 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌글라사 21년' WHERE name = 'Glenglassaugh 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌글라사 12년 셰리 캐스크' WHERE name = 'Glenglassaugh 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌글라사 12년 캐스크 스트렝스' WHERE name = 'Glenglassaugh 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '아드벡 10년' WHERE name = 'Ardbeg 10 Year';
UPDATE whisky_note.catalog SET name_ko = '아드벡 우가달' WHERE name = 'Ardbeg Uigeadail';
UPDATE whisky_note.catalog SET name_ko = '아드벡 코리브레칸' WHERE name = 'Ardbeg Corryvreckan';
UPDATE whisky_note.catalog SET name_ko = '아드벡 안 오' WHERE name = 'Ardbeg An Oa';
UPDATE whisky_note.catalog SET name_ko = '아드벡 켈피' WHERE name = 'Ardbeg Kelpie';
UPDATE whisky_note.catalog SET name_ko = '라가불린 16년' WHERE name = 'Lagavulin 16 Year';
UPDATE whisky_note.catalog SET name_ko = '라가불린 12년' WHERE name = 'Lagavulin 12 Year';
UPDATE whisky_note.catalog SET name_ko = '라가불린 디스틸러스 에디션' WHERE name = 'Lagavulin Distillers Edition';
UPDATE whisky_note.catalog SET name_ko = '라가불린 8년' WHERE name = 'Lagavulin 8 Year';
UPDATE whisky_note.catalog SET name_ko = '라가불린 12년 캐스크 스트렝스' WHERE name = 'Lagavulin 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '라프로익 10년' WHERE name = 'Laphroaig 10 Year';
UPDATE whisky_note.catalog SET name_ko = '라프로익 쿼터 캐스크' WHERE name = 'Laphroaig Quarter Cask';
UPDATE whisky_note.catalog SET name_ko = '라프로익 트리플 우드' WHERE name = 'Laphroaig Triple Wood';
UPDATE whisky_note.catalog SET name_ko = '라프로익 12년' WHERE name = 'Laphroaig 12 Year';
UPDATE whisky_note.catalog SET name_ko = '라프로익 로어' WHERE name = 'Laphroaig Lore';
UPDATE whisky_note.catalog SET name_ko = '보모어 12년' WHERE name = 'Bowmore 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '보모어 18년' WHERE name = 'Bowmore 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '보모어 25년' WHERE name = 'Bowmore 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '보모어 다키스트 2022' WHERE name = 'Bowmore Darkest 2022';
UPDATE whisky_note.catalog SET name_ko = '브룩라디 클래식 라디' WHERE name = 'Bruichladdich Classic Laddie';
UPDATE whisky_note.catalog SET name_ko = '브룩라디 클래식 라디 12년' WHERE name = 'Bruichladdich The Classic Laddie 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '브룩라디 포트 샬럿 12년' WHERE name = 'Bruichladdich Port Charlotte 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '브룩라디 옥토모어 10.0' WHERE name = 'Bruichladdich Octomore 10.0';
UPDATE whisky_note.catalog SET name_ko = '포트 샬럿 12년' WHERE name = 'Port Charlotte 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '포트 샬럿 18년' WHERE name = 'Port Charlotte 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '포트 샬럿 30년' WHERE name = 'Port Charlotte 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '옥토모어 12.1' WHERE name = 'Octomore 12.1';
UPDATE whisky_note.catalog SET name_ko = '옥토모어 14.2' WHERE name = 'Octomore 14.2';
UPDATE whisky_note.catalog SET name_ko = '옥토모어 16.1' WHERE name = 'Octomore 16.1';
UPDATE whisky_note.catalog SET name_ko = '카올 일라 12년' WHERE name = 'Caol Ila 12 Year';
UPDATE whisky_note.catalog SET name_ko = '카올 일라 18년' WHERE name = 'Caol Ila 18 Year';
UPDATE whisky_note.catalog SET name_ko = '카올 일라 25년' WHERE name = 'Caol Ila 25 Year';
UPDATE whisky_note.catalog SET name_ko = '카올 일라 12년 캐스크 스트렝스' WHERE name = 'Caol Ila 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '카올 일라 2021 아일라 싱글몰트' WHERE name = 'Caol Ila 2021 Islay Single Malt';
UPDATE whisky_note.catalog SET name_ko = '부나하벤 12년' WHERE name = 'Bunnahabhain 12 Year';
UPDATE whisky_note.catalog SET name_ko = '부나하벤 18년' WHERE name = 'Bunnahabhain 18 Year';
UPDATE whisky_note.catalog SET name_ko = '부나하벤 21년' WHERE name = 'Bunnahabhain 21 Year';
UPDATE whisky_note.catalog SET name_ko = '부나하벤 12년 캐스크 스트렝스' WHERE name = 'Bunnahabhain 12 Year Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '부나하벤 토이차흐' WHERE name = 'Bunnahabhain Toiteach';
UPDATE whisky_note.catalog SET name_ko = '킬호만 마커 베이' WHERE name = 'Kilchoman Machir Bay';
UPDATE whisky_note.catalog SET name_ko = '킬호만 12년' WHERE name = 'Kilchoman 12 Year';
UPDATE whisky_note.catalog SET name_ko = '킬호만 15년' WHERE name = 'Kilchoman 15 Year';
UPDATE whisky_note.catalog SET name_ko = '킬호만 25년' WHERE name = 'Kilchoman 25 Year';
UPDATE whisky_note.catalog SET name_ko = '킬호만 마커 베이 캐스크 스트렝스' WHERE name = 'Kilchoman Machir Bay Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '아드나호 10년' WHERE name = 'Ardnahoe 10 Year';
UPDATE whisky_note.catalog SET name_ko = '아드나호 12년' WHERE name = 'Ardnahoe 12 Year';
UPDATE whisky_note.catalog SET name_ko = '아드나호 18년' WHERE name = 'Ardnahoe 18 Year';
UPDATE whisky_note.catalog SET name_ko = '아드나호 2022 릴리즈' WHERE name = 'Ardnahoe 2022 Release';
UPDATE whisky_note.catalog SET name_ko = '아드나호 캐스크 스트렝스' WHERE name = 'Ardnahoe Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '탈리스커 10년' WHERE name = 'Talisker 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '탈리스커 스톰' WHERE name = 'Talisker Storm';
UPDATE whisky_note.catalog SET name_ko = '탈리스커 18년' WHERE name = 'Talisker 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '탈리스커 25년' WHERE name = 'Talisker 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '탈리스커 디스틸러스 에디션' WHERE name = 'Talisker Distillers Edition';
UPDATE whisky_note.catalog SET name_ko = '탈리스커 57°' WHERE name = 'Talisker 57°';
UPDATE whisky_note.catalog SET name_ko = '하이랜드 파크 12년' WHERE name = 'Highland Park 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '하이랜드 파크 18년' WHERE name = 'Highland Park 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '하이랜드 파크 25년' WHERE name = 'Highland Park 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '하이랜드 파크 발키리' WHERE name = 'Highland Park Valkyrie';
UPDATE whisky_note.catalog SET name_ko = '하이랜드 파크 캐스크 스트렝스' WHERE name = 'Highland Park Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '스카파 12년' WHERE name = 'Scapa 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스카파 18년' WHERE name = 'Scapa 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스카파 21년' WHERE name = 'Scapa 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스카파 스키렌' WHERE name = 'Scapa Skiren';
UPDATE whisky_note.catalog SET name_ko = '스카파 30년' WHERE name = 'Scapa 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '주라 12년' WHERE name = 'Jura 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '주라 18년' WHERE name = 'Jura 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '주라 15년' WHERE name = 'Jura 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '주라 프로페시' WHERE name = 'Jura Prophecy';
UPDATE whisky_note.catalog SET name_ko = '주라 슈퍼스티션' WHERE name = 'Jura Superstition';
UPDATE whisky_note.catalog SET name_ko = '아란 10년' WHERE name = 'Arran 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아란 14년' WHERE name = 'Arran 14 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아란 18년' WHERE name = 'Arran 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아란 패밀리 리저브' WHERE name = 'Arran Family Reserve';
UPDATE whisky_note.catalog SET name_ko = '아란 21년' WHERE name = 'Arran 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토버모리 12년' WHERE name = 'Tobermory 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토버모리 21년' WHERE name = 'Tobermory 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토버모리 30년' WHERE name = 'Tobermory 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토버모리 15년' WHERE name = 'Tobermory 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토버모리 18년' WHERE name = 'Tobermory 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레칙 10년' WHERE name = 'Ledaig 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레칙 12년' WHERE name = 'Ledaig 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레칙 15년' WHERE name = 'Ledaig 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레칙 18년' WHERE name = 'Ledaig 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레칙 21년' WHERE name = 'Ledaig 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레칙 30년' WHERE name = 'Ledaig 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토라베이그 10년' WHERE name = 'Torabhaig 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토라베이그 12년' WHERE name = 'Torabhaig 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '토라베이그 15년 셰리 캐스크 피니시' WHERE name = 'Torabhaig 15 Year Old Sherry Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '아일 오브 라세이 10년' WHERE name = 'Isle of Raasay 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아일 오브 라세이 12년' WHERE name = 'Isle of Raasay 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '아일 오브 라세이 15년 포트 캐스크 피니시' WHERE name = 'Isle of Raasay 15 Year Old Port Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '로크란자 12년' WHERE name = 'Lochranza 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로크란자 15년' WHERE name = 'Lochranza 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로크란자 18년 셰리 캐스크' WHERE name = 'Lochranza 18 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '스프링뱅크 10년' WHERE name = 'Springbank 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스프링뱅크 12년' WHERE name = 'Springbank 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스프링뱅크 15년' WHERE name = 'Springbank 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스프링뱅크 18년' WHERE name = 'Springbank 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스프링뱅크 10년 캐스크 스트렝스' WHERE name = 'Springbank 10 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '스프링뱅크 12년 포트 우드 피니시' WHERE name = 'Springbank 12 Year Old Port Wood Finish';
UPDATE whisky_note.catalog SET name_ko = '스프링뱅크 12년 피티드' WHERE name = 'Springbank 12 Year Old Peated';
UPDATE whisky_note.catalog SET name_ko = '롱로우 10년' WHERE name = 'Longrow 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '롱로우 12년' WHERE name = 'Longrow 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '롱로우 15년' WHERE name = 'Longrow 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '롱로우 12년 캐스크 스트렝스' WHERE name = 'Longrow 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '롱로우 12년 포트 캐스크' WHERE name = 'Longrow 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '헤이즐번 10년' WHERE name = 'Hazelburn 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '헤이즐번 12년' WHERE name = 'Hazelburn 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '헤이즐번 15년' WHERE name = 'Hazelburn 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '헤이즐번 12년 캐스크 스트렝스' WHERE name = 'Hazelburn 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '헤이즐번 12년 셰리 캐스크' WHERE name = 'Hazelburn 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '글렌 스코샤 10년' WHERE name = 'Glen Scotia 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 스코샤 12년' WHERE name = 'Glen Scotia 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 스코샤 15년' WHERE name = 'Glen Scotia 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌 스코샤 12년 캐스크 스트렝스' WHERE name = 'Glen Scotia 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '글렌 스코샤 12년 포트 캐스크' WHERE name = 'Glen Scotia 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '킬커란 12년' WHERE name = 'Kilkerran 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '킬커란 15년' WHERE name = 'Kilkerran 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '킬커란 18년' WHERE name = 'Kilkerran 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '킬커란 12년 캐스크 스트렝스' WHERE name = 'Kilkerran 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '킬커란 12년 셰리 캐스크' WHERE name = 'Kilkerran 12 Year Old Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '킬커란 12년 포트 캐스크' WHERE name = 'Kilkerran 12 Year Old Port Cask';
UPDATE whisky_note.catalog SET name_ko = '오켄토션 아메리칸 오크' WHERE name = 'Auchentoshan American Oak';
UPDATE whisky_note.catalog SET name_ko = '오켄토션 12년' WHERE name = 'Auchentoshan 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '오켄토션 쓰리 우드' WHERE name = 'Auchentoshan Three Wood';
UPDATE whisky_note.catalog SET name_ko = '오켄토션 21년' WHERE name = 'Auchentoshan 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '오켄토션 30년' WHERE name = 'Auchentoshan 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌킨치 12년' WHERE name = 'Glenkinchie 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌킨치 18년' WHERE name = 'Glenkinchie 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌킨치 21년' WHERE name = 'Glenkinchie 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '글렌킨치 디스틸러리 익스클루시브 2022' WHERE name = 'Glenkinchie Distillery Exclusive 2022';
UPDATE whisky_note.catalog SET name_ko = '블라드녹 12년' WHERE name = 'Bladnoch 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블라드녹 18년' WHERE name = 'Bladnoch 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블라드녹 21년' WHERE name = 'Bladnoch 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블라드녹 30년' WHERE name = 'Bladnoch 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '블라드녹 리미티드 에디션 2021 포트 캐스크' WHERE name = 'Bladnoch Limited Edition 2021 Port Cask';
UPDATE whisky_note.catalog SET name_ko = '킹스반스 10년' WHERE name = 'Kingsbarns 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '킹스반스 12년' WHERE name = 'Kingsbarns 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '킹스반스 18년' WHERE name = 'Kingsbarns 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '킹스반스 2022 리미티드 릴리즈' WHERE name = 'Kingsbarns 2022 Limited Release';
UPDATE whisky_note.catalog SET name_ko = '로즈뱅크 10년' WHERE name = 'Rosebank 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로즈뱅크 12년' WHERE name = 'Rosebank 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로즈뱅크 18년' WHERE name = 'Rosebank 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '로즈뱅크 2021 리미티드 에디션' WHERE name = 'Rosebank 2021 Limited Edition';
UPDATE whisky_note.catalog SET name_ko = '조니워커 레드 라벨' WHERE name = 'Johnnie Walker Red Label';
UPDATE whisky_note.catalog SET name_ko = '조니워커 블랙 라벨' WHERE name = 'Johnnie Walker Black Label';
UPDATE whisky_note.catalog SET name_ko = '조니워커 더블 블랙' WHERE name = 'Johnnie Walker Double Black';
UPDATE whisky_note.catalog SET name_ko = '조니워커 그린 라벨' WHERE name = 'Johnnie Walker Green Label';
UPDATE whisky_note.catalog SET name_ko = '조니워커 골드 라벨 리저브' WHERE name = 'Johnnie Walker Gold Label Reserve';
UPDATE whisky_note.catalog SET name_ko = '조니워커 플래티넘 라벨' WHERE name = 'Johnnie Walker Platinum Label';
UPDATE whisky_note.catalog SET name_ko = '조니워커 블루 라벨' WHERE name = 'Johnnie Walker Blue Label';
UPDATE whisky_note.catalog SET name_ko = '조니워커 18년' WHERE name = 'Johnnie Walker 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '조니워커 21년' WHERE name = 'Johnnie Walker 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 12년' WHERE name = 'Chivas Regal 12 Year';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 18년' WHERE name = 'Chivas Regal 18 Year';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 25년' WHERE name = 'Chivas Regal 25 Year';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 12년 트리플 우드' WHERE name = 'Chivas Regal 12 Year Triple Wood';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 18년 미즈나라' WHERE name = 'Chivas Regal 18 Year Mizunara';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 XV' WHERE name = 'Chivas Regal XV';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 12년 골드' WHERE name = 'Chivas Regal 12 Year Gold';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 21년' WHERE name = 'Chivas Regal 21 Year';
UPDATE whisky_note.catalog SET name_ko = '시바스 리갈 30년' WHERE name = 'Chivas Regal 30 Year';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 파이니스트' WHERE name = 'Ballantine''s Finest';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 12년' WHERE name = 'Ballantine''s 12 Year';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 17년' WHERE name = 'Ballantine''s 17 Year';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 21년' WHERE name = 'Ballantine''s 21 Year';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 30년' WHERE name = 'Ballantine''s 30 Year';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 12년 트리플 우드' WHERE name = 'Ballantine''s 12 Year Triple Wood';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 12년 스페셜 리저브' WHERE name = 'Ballantine''s 12 Year Special Reserve';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 21년 리미티드 에디션' WHERE name = 'Ballantine''s 21 Year Limited Edition';
UPDATE whisky_note.catalog SET name_ko = '발렌타인 30년 리미티드 에디션' WHERE name = 'Ballantine''s 30 Year Limited Edition';
UPDATE whisky_note.catalog SET name_ko = '듀어스 화이트 라벨' WHERE name = 'Dewar''s White Label';
UPDATE whisky_note.catalog SET name_ko = '듀어스 12년' WHERE name = 'Dewar''s 12 Year';
UPDATE whisky_note.catalog SET name_ko = '듀어스 15년' WHERE name = 'Dewar''s 15 Year';
UPDATE whisky_note.catalog SET name_ko = '듀어스 18년' WHERE name = 'Dewar''s 18 Year';
UPDATE whisky_note.catalog SET name_ko = '듀어스 21년' WHERE name = 'Dewar''s 21 Year';
UPDATE whisky_note.catalog SET name_ko = '듀어스 캐리비안 스무스' WHERE name = 'Dewar''s Caribbean Smooth';
UPDATE whisky_note.catalog SET name_ko = '듀어스 시그니처' WHERE name = 'Dewar''s Signature';
UPDATE whisky_note.catalog SET name_ko = '페이머스 그라우스' WHERE name = 'The Famous Grouse';
UPDATE whisky_note.catalog SET name_ko = '페이머스 그라우스 18년' WHERE name = 'The Famous Grouse 18 Year';
UPDATE whisky_note.catalog SET name_ko = '페이머스 그라우스 21년' WHERE name = 'The Famous Grouse 21 Year';
UPDATE whisky_note.catalog SET name_ko = '페이머스 그라우스 스모키' WHERE name = 'The Famous Grouse Smoky';
UPDATE whisky_note.catalog SET name_ko = '페이머스 그라우스 30년' WHERE name = 'The Famous Grouse 30 Year';
UPDATE whisky_note.catalog SET name_ko = '그란츠 패밀리 리저브' WHERE name = 'Grant''s Family Reserve';
UPDATE whisky_note.catalog SET name_ko = '그란츠 트리플 우드' WHERE name = 'Grant''s Triple Wood';
UPDATE whisky_note.catalog SET name_ko = '그란츠 10년' WHERE name = 'Grant''s 10 Year';
UPDATE whisky_note.catalog SET name_ko = '그란츠 12년' WHERE name = 'Grant''s 12 Year';
UPDATE whisky_note.catalog SET name_ko = '그란츠 18년' WHERE name = 'Grant''s 18 Year';
UPDATE whisky_note.catalog SET name_ko = '그란츠 21년' WHERE name = 'Grant''s 21 Year';
UPDATE whisky_note.catalog SET name_ko = '그란츠 30년' WHERE name = 'Grant''s 30 Year';
UPDATE whisky_note.catalog SET name_ko = '커티삭 오리지널' WHERE name = 'Cutty Sark Original';
UPDATE whisky_note.catalog SET name_ko = '커티삭 12년' WHERE name = 'Cutty Sark 12 Year';
UPDATE whisky_note.catalog SET name_ko = '커티삭 18년' WHERE name = 'Cutty Sark 18 Year';
UPDATE whisky_note.catalog SET name_ko = '커티삭 21년' WHERE name = 'Cutty Sark 21 Year';
UPDATE whisky_note.catalog SET name_ko = '커티삭 30년' WHERE name = 'Cutty Sark 30 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 살루트 21년' WHERE name = 'Royal Salute 21 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 살루트 38년' WHERE name = 'Royal Salute 38 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 살루트 40년' WHERE name = 'Royal Salute 40 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 살루트 62년' WHERE name = 'Royal Salute 62 Year';
UPDATE whisky_note.catalog SET name_ko = '로열 살루트 100주년' WHERE name = 'Royal Salute 100th Anniversary';
UPDATE whisky_note.catalog SET name_ko = '올드 파 12년' WHERE name = 'Old Parr 12 Year';
UPDATE whisky_note.catalog SET name_ko = '올드 파 21년' WHERE name = 'Old Parr 21 Year';
UPDATE whisky_note.catalog SET name_ko = '올드 파 30년' WHERE name = 'Old Parr 30 Year';
UPDATE whisky_note.catalog SET name_ko = '올드 파 트리뷰트' WHERE name = 'Old Parr Tribute';
UPDATE whisky_note.catalog SET name_ko = '올드 파 12년 (버번 캐스크)' WHERE name = 'Old Parr 12 Year (Bourbon Cask)';
UPDATE whisky_note.catalog SET name_ko = 'J&B 레어' WHERE name = 'J&B Rare';
UPDATE whisky_note.catalog SET name_ko = 'J&B 18년' WHERE name = 'J&B 18 Year';
UPDATE whisky_note.catalog SET name_ko = 'J&B 21년' WHERE name = 'J&B 21 Year';
UPDATE whisky_note.catalog SET name_ko = 'J&B 12년' WHERE name = 'J&B 12 Year';
UPDATE whisky_note.catalog SET name_ko = 'J&B 12년 (셰리 캐스크)' WHERE name = 'J&B 12 Year (Sherry Cask)';
UPDATE whisky_note.catalog SET name_ko = '화이트 앤 맥케이 12년' WHERE name = 'Whyte & Mackay 12 Year';
UPDATE whisky_note.catalog SET name_ko = '화이트 앤 맥케이 18년' WHERE name = 'Whyte & Mackay 18 Year';
UPDATE whisky_note.catalog SET name_ko = '화이트 앤 맥케이 21년' WHERE name = 'Whyte & Mackay 21 Year';
UPDATE whisky_note.catalog SET name_ko = '화이트 앤 맥케이 30년' WHERE name = 'Whyte & Mackay 30 Year';
UPDATE whisky_note.catalog SET name_ko = '화이트 앤 맥케이 12년 (셰리 캐스크)' WHERE name = 'Whyte & Mackay 12 Year (Sherry Cask)';
UPDATE whisky_note.catalog SET name_ko = '몽키 숄더 오리지널' WHERE name = 'Monkey Shoulder Original';
UPDATE whisky_note.catalog SET name_ko = '몽키 숄더 30년' WHERE name = 'Monkey Shoulder 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '몽키 숄더 10년' WHERE name = 'Monkey Shoulder 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '카퍼 독 12년' WHERE name = 'Copper Dog 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '카퍼 독 18년' WHERE name = 'Copper Dog 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '카퍼 독 21년' WHERE name = 'Copper Dog 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '조니워커 그린 라벨 15년' WHERE name = 'Johnnie Walker Green Label 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '조니워커 그린 라벨 21년' WHERE name = 'Johnnie Walker Green Label 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '빅 피트 12년' WHERE name = 'Big Peat 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '빅 피트 15년' WHERE name = 'Big Peat 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '빅 피트 18년' WHERE name = 'Big Peat 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스캘리왜그 12년' WHERE name = 'Scallywag 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스캘리왜그 15년' WHERE name = 'Scallywag 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '스캘리왜그 18년' WHERE name = 'Scallywag 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '티모러스 비스티 12년' WHERE name = 'Timorous Beastie 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '티모러스 비스티 15년' WHERE name = 'Timorous Beastie 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '티모러스 비스티 18년' WHERE name = 'Timorous Beastie 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '헤이그 클럽' WHERE name = 'Haig Club';
UPDATE whisky_note.catalog SET name_ko = '헤이그 클럽 12년' WHERE name = 'Haig Club 12 Year';
UPDATE whisky_note.catalog SET name_ko = '헤이그 클럽 18년' WHERE name = 'Haig Club 18 Year';
UPDATE whisky_note.catalog SET name_ko = '헤이그 클럽 셰리 캐스크' WHERE name = 'Haig Club Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '헤이그 클럽 리미티드 에디션 캐스크 스트렝스' WHERE name = 'Haig Club Limited Edition Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '거번 싱글몰트' WHERE name = 'Girvan Single Malt';
UPDATE whisky_note.catalog SET name_ko = '거번 12년' WHERE name = 'Girvan 12 Year';
UPDATE whisky_note.catalog SET name_ko = '거번 15년' WHERE name = 'Girvan 15 Year';
UPDATE whisky_note.catalog SET name_ko = '거번 18년' WHERE name = 'Girvan 18 Year';
UPDATE whisky_note.catalog SET name_ko = '거번 30년' WHERE name = 'Girvan 30 Year';
UPDATE whisky_note.catalog SET name_ko = '카메론브리지 싱글 그레인' WHERE name = 'Cameronbridge Single Grain';
UPDATE whisky_note.catalog SET name_ko = '카메론브리지 12년' WHERE name = 'Cameronbridge 12 Year';
UPDATE whisky_note.catalog SET name_ko = '카메론브리지 15년' WHERE name = 'Cameronbridge 15 Year';
UPDATE whisky_note.catalog SET name_ko = '카메론브리지 18년' WHERE name = 'Cameronbridge 18 Year';
UPDATE whisky_note.catalog SET name_ko = '카메론브리지 30년' WHERE name = 'Cameronbridge 30 Year';
UPDATE whisky_note.catalog SET name_ko = '노스 브리티시 12년' WHERE name = 'North British 12 Year';
UPDATE whisky_note.catalog SET name_ko = '노스 브리티시 15년' WHERE name = 'North British 15 Year';
UPDATE whisky_note.catalog SET name_ko = '노스 브리티시 18년' WHERE name = 'North British 18 Year';
UPDATE whisky_note.catalog SET name_ko = '노스 브리티시 21년' WHERE name = 'North British 21 Year';
UPDATE whisky_note.catalog SET name_ko = '노스 브리티시 30년' WHERE name = 'North British 30 Year';
UPDATE whisky_note.catalog SET name_ko = '버팔로 트레이스 버번' WHERE name = 'Buffalo Trace Bourbon';
UPDATE whisky_note.catalog SET name_ko = '버팔로 트레이스 12년 버번' WHERE name = 'Buffalo Trace 12 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '버팔로 트레이스 17년 버번' WHERE name = 'Buffalo Trace 17 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '버팔로 트레이스 20년 버번' WHERE name = 'Buffalo Trace 20 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '버팔로 트레이스 라이' WHERE name = 'Buffalo Trace Rye';
UPDATE whisky_note.catalog SET name_ko = '이글 레어 10년 버번' WHERE name = 'Eagle Rare 10 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '이글 레어 12년 버번' WHERE name = 'Eagle Rare 12 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '이글 레어 17년 버번' WHERE name = 'Eagle Rare 17 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '이글 레어 6년 버번' WHERE name = 'Eagle Rare 6 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '블랜튼스 싱글 배럴 버번' WHERE name = 'Blanton''s Single Barrel Bourbon';
UPDATE whisky_note.catalog SET name_ko = '블랜튼스 골드 에디션' WHERE name = 'Blanton''s Gold Edition';
UPDATE whisky_note.catalog SET name_ko = '블랜튼스 12년 버번' WHERE name = 'Blanton''s 12 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'W.L. 웰러 스페셜 리저브 버번' WHERE name = 'W.L. Weller Special Reserve Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'W.L. 웰러 앤티크 107 버번' WHERE name = 'W.L. Weller Antique 107 Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'W.L. 웰러 12년 버번' WHERE name = 'W.L. Weller 12 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'W.L. 웰러 15년 버번' WHERE name = 'W.L. Weller 15 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'E.H. 테일러 주니어 스트레이트 라이' WHERE name = 'E.H. Taylor Jr. Straight Rye Whiskey';
UPDATE whisky_note.catalog SET name_ko = 'E.H. 테일러 스몰 배치 버번' WHERE name = 'E.H. Taylor Small Batch Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'E.H. 테일러 싱글 배럴 버번' WHERE name = 'E.H. Taylor Single Barrel Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'E.H. 테일러 12년 버번' WHERE name = 'E.H. Taylor 12 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = 'E.H. 테일러 15년 버번' WHERE name = 'E.H. Taylor 15 Year Bourbon';
UPDATE whisky_note.catalog SET name_ko = '메이커스 마크' WHERE name = 'Maker''s Mark';
UPDATE whisky_note.catalog SET name_ko = '메이커스 마크 46' WHERE name = 'Maker''s Mark 46';
UPDATE whisky_note.catalog SET name_ko = '메이커스 마크 101' WHERE name = 'Maker''s Mark 101';
UPDATE whisky_note.catalog SET name_ko = '메이커스 마크 프라이빗 셀렉트' WHERE name = 'Maker''s Mark Private Select';
UPDATE whisky_note.catalog SET name_ko = '와일드 터키 101' WHERE name = 'Wild Turkey 101';
UPDATE whisky_note.catalog SET name_ko = '와일드 터키 레어 브리드' WHERE name = 'Wild Turkey Rare Breed';
UPDATE whisky_note.catalog SET name_ko = '와일드 터키 81' WHERE name = 'Wild Turkey 81';
UPDATE whisky_note.catalog SET name_ko = '와일드 터키 마스터스 킵' WHERE name = 'Wild Turkey Master''s Keep';
UPDATE whisky_note.catalog SET name_ko = '러셀스 리저브 10년' WHERE name = 'Russell''s Reserve 10 Year';
UPDATE whisky_note.catalog SET name_ko = '러셀스 리저브 싱글 배럴' WHERE name = 'Russell''s Reserve Single Barrel';
UPDATE whisky_note.catalog SET name_ko = '러셀스 리저브 22년' WHERE name = 'Russell''s Reserve 22 Year';
UPDATE whisky_note.catalog SET name_ko = '러셀스 리저브 30년' WHERE name = 'Russell''s Reserve 30 Year';
UPDATE whisky_note.catalog SET name_ko = '포 로지스 싱글 배럴' WHERE name = 'Four Roses Single Barrel';
UPDATE whisky_note.catalog SET name_ko = '포 로지스 스몰 배치' WHERE name = 'Four Roses Small Batch';
UPDATE whisky_note.catalog SET name_ko = '포 로지스 18년' WHERE name = 'Four Roses 18 Year';
UPDATE whisky_note.catalog SET name_ko = '포 로지스 리미티드 에디션' WHERE name = 'Four Roses Limited Edition';
UPDATE whisky_note.catalog SET name_ko = '짐빔 화이트 라벨' WHERE name = 'Jim Beam White Label';
UPDATE whisky_note.catalog SET name_ko = '짐빔 블랙' WHERE name = 'Jim Beam Black';
UPDATE whisky_note.catalog SET name_ko = '짐빔 데블스 컷' WHERE name = 'Jim Beam Devil''s Cut';
UPDATE whisky_note.catalog SET name_ko = '짐빔 더블 오크' WHERE name = 'Jim Beam Double Oak';
UPDATE whisky_note.catalog SET name_ko = '짐빔 라이' WHERE name = 'Jim Beam Rye';
UPDATE whisky_note.catalog SET name_ko = '짐빔 12년' WHERE name = 'Jim Beam 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 9년' WHERE name = 'Knob Creek 9 Year Old';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 싱글 배럴' WHERE name = 'Knob Creek Single Barrel';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 12년' WHERE name = 'Knob Creek 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 라이' WHERE name = 'Knob Creek Rye';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 15년' WHERE name = 'Knob Creek 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '부커스 버번' WHERE name = 'Booker''s Bourbon';
UPDATE whisky_note.catalog SET name_ko = '부커스 라이' WHERE name = 'Booker''s Rye';
UPDATE whisky_note.catalog SET name_ko = '부커스 12년' WHERE name = 'Booker''s 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '베이즐 헤이든' WHERE name = 'Basil Hayden''s';
UPDATE whisky_note.catalog SET name_ko = '베이즐 헤이든 10년' WHERE name = 'Basil Hayden''s 10 Year Old';
UPDATE whisky_note.catalog SET name_ko = '베이즐 헤이든 라이' WHERE name = 'Basil Hayden''s Rye';
UPDATE whisky_note.catalog SET name_ko = '올드 그랜드대드 본디드' WHERE name = 'Old Grand-Dad Bonded';
UPDATE whisky_note.catalog SET name_ko = '올드 그랜드대드 114' WHERE name = 'Old Grand-Dad 114';
UPDATE whisky_note.catalog SET name_ko = '올드 그랜드대드 8년' WHERE name = 'Old Grand-Dad 8 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올드 그랜드대드 12년' WHERE name = 'Old Grand-Dad 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '올드 그랜드대드 라이' WHERE name = 'Old Grand-Dad Rye';
UPDATE whisky_note.catalog SET name_ko = '우드포드 리저브 켄터키 스트레이트 버번' WHERE name = 'Woodford Reserve Kentucky Straight Bourbon Whiskey';
UPDATE whisky_note.catalog SET name_ko = '우드포드 리저브 더블 오크드' WHERE name = 'Woodford Reserve Double Oaked';
UPDATE whisky_note.catalog SET name_ko = '우드포드 리저브 마스터스 컬렉션 2010' WHERE name = 'Woodford Reserve Master''s Collection 2010';
UPDATE whisky_note.catalog SET name_ko = '우드포드 리저브 마스터스 컬렉션 2014' WHERE name = 'Woodford Reserve Master''s Collection 2014';
UPDATE whisky_note.catalog SET name_ko = '우드포드 리저브 라이' WHERE name = 'Woodford Reserve Rye Whiskey';
UPDATE whisky_note.catalog SET name_ko = '올드 포레스터 86 프루프 켄터키 스트레이트 버번' WHERE name = 'Old Forester 86 Proof Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '올드 포레스터 100 프루프 켄터키 스트레이트 버번' WHERE name = 'Old Forester 100 Proof Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '올드 포레스터 버스데이 버번' WHERE name = 'Old Forester Birthday Bourbon';
UPDATE whisky_note.catalog SET name_ko = '올드 포레스터 1897 켄터키 스트레이트 버번' WHERE name = 'Old Forester 1897 Kentucky Straight Bourbon Whiskey';
UPDATE whisky_note.catalog SET name_ko = '올드 포레스터 12년 켄터키 스트레이트 버번' WHERE name = 'Old Forester 12 Year Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '일라이자 크레이그 스몰 배치 버번' WHERE name = 'Elijah Craig Small Batch Bourbon';
UPDATE whisky_note.catalog SET name_ko = '일라이자 크레이그 배럴 프루프' WHERE name = 'Elijah Craig Barrel Proof';
UPDATE whisky_note.catalog SET name_ko = '일라이자 크레이그 12년 스몰 배치' WHERE name = 'Elijah Craig 12 Year Small Batch';
UPDATE whisky_note.catalog SET name_ko = '일라이자 크레이그 토스티드 오크' WHERE name = 'Elijah Craig Toasted Oak';
UPDATE whisky_note.catalog SET name_ko = '일라이자 크레이그 18년 스몰 배치' WHERE name = 'Elijah Craig 18 Year Small Batch';
UPDATE whisky_note.catalog SET name_ko = '에반 윌리엄스 블랙 라벨 켄터키 스트레이트 버번' WHERE name = 'Evan Williams Black Label Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '에반 윌리엄스 12년 켄터키 스트레이트 버번' WHERE name = 'Evan Williams 12 Year Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '에반 윌리엄스 싱글 배럴' WHERE name = 'Evan Williams Single Barrel';
UPDATE whisky_note.catalog SET name_ko = '에반 윌리엄스 보틀드 인 본드' WHERE name = 'Evan Williams Bottled-in-Bond';
UPDATE whisky_note.catalog SET name_ko = '에반 윌리엄스 18년 켄터키 스트레이트 버번' WHERE name = 'Evan Williams 18 Year Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '믹터스 오리지널 US*1 라이' WHERE name = 'Michter''s Original US*1 Rye Whiskey';
UPDATE whisky_note.catalog SET name_ko = '믹터스 US*1 싱글 배럴 라이' WHERE name = 'Michter''s US*1 Single Barrel Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 10년 스트레이트 라이' WHERE name = 'Michter''s 10 Year Old Straight Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 20년 스트레이트 라이' WHERE name = 'Michter''s 20 Year Old Straight Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 25년 스트레이트 라이' WHERE name = 'Michter''s 25 Year Old Straight Rye';
UPDATE whisky_note.catalog SET name_ko = '1792 풀 프루프 버번' WHERE name = '1792 Full Proof Bourbon';
UPDATE whisky_note.catalog SET name_ko = '1792 스몰 배치 버번' WHERE name = '1792 Small Batch Bourbon';
UPDATE whisky_note.catalog SET name_ko = '1792 싱글 배럴 버번' WHERE name = '1792 Single Barrel Bourbon';
UPDATE whisky_note.catalog SET name_ko = '1792 12년 버번' WHERE name = '1792 12 Year Old Bourbon';
UPDATE whisky_note.catalog SET name_ko = '1792 18년 버번' WHERE name = '1792 18 Year Old Bourbon';
UPDATE whisky_note.catalog SET name_ko = '헤븐힐 보틀드 인 본드 켄터키 스트레이트 버번' WHERE name = 'Heaven Hill Bottled-in-Bond Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '헤븐힐 8년 켄터키 스트레이트 버번' WHERE name = 'Heaven Hill 8 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '헤븐힐 12년 켄터키 스트레이트 버번' WHERE name = 'Heaven Hill 12 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '헤븐힐 18년 켄터키 스트레이트 버번' WHERE name = 'Heaven Hill 18 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '헤븐힐 20년 켄터키 스트레이트 버번' WHERE name = 'Heaven Hill 20 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '베리 올드 바턴 8년 켄터키 스트레이트 버번' WHERE name = 'Very Old Barton 8 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '베리 올드 바턴 12년 켄터키 스트레이트 버번' WHERE name = 'Very Old Barton 12 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '베리 올드 바턴 15년 켄터키 스트레이트 버번' WHERE name = 'Very Old Barton 15 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '베리 올드 바턴 20년 켄터키 스트레이트 버번' WHERE name = 'Very Old Barton 20 Year Old Kentucky Straight Bourbon';
UPDATE whisky_note.catalog SET name_ko = '라세니 스몰 배치 버번' WHERE name = 'Larceny Small Batch Bourbon';
UPDATE whisky_note.catalog SET name_ko = '라세니 8년 버번' WHERE name = 'Larceny 8 Year Old Bourbon';
UPDATE whisky_note.catalog SET name_ko = '라세니 12년 버번' WHERE name = 'Larceny 12 Year Old Bourbon';
UPDATE whisky_note.catalog SET name_ko = '라세니 18년 버번' WHERE name = 'Larceny 18 Year Old Bourbon';
UPDATE whisky_note.catalog SET name_ko = '라세니 20년 버번' WHERE name = 'Larceny 20 Year Old Bourbon';
UPDATE whisky_note.catalog SET name_ko = '리튼하우스 라이 100 프루프' WHERE name = 'Rittenhouse Rye 100 Proof';
UPDATE whisky_note.catalog SET name_ko = '리튼하우스 라이 110 프루프' WHERE name = 'Rittenhouse Rye 110 Proof';
UPDATE whisky_note.catalog SET name_ko = '리튼하우스 라이 캐스크 스트렝스' WHERE name = 'Rittenhouse Rye Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '사제락 12년 라이' WHERE name = 'Sazerac 12 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '사제락 18년 라이' WHERE name = 'Sazerac 18 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '사제락 라이 (NAS)' WHERE name = 'Sazerac Rye (NAS)';
UPDATE whisky_note.catalog SET name_ko = '위슬피그 라이' WHERE name = 'WhistlePig Rye';
UPDATE whisky_note.catalog SET name_ko = '위슬피그 10년 스트레이트 라이' WHERE name = 'WhistlePig 10 Year Straight Rye';
UPDATE whisky_note.catalog SET name_ko = '위슬피그 12년 스트레이트 라이' WHERE name = 'WhistlePig 12 Year Straight Rye';
UPDATE whisky_note.catalog SET name_ko = '위슬피그 15년 스트레이트 라이' WHERE name = 'WhistlePig 15 Year Straight Rye';
UPDATE whisky_note.catalog SET name_ko = '위슬피그 더 보스 호그' WHERE name = 'WhistlePig The Boss Hog';
UPDATE whisky_note.catalog SET name_ko = '믹터스 라이' WHERE name = 'Michter''s Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 10년 라이' WHERE name = 'Michter''s 10 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 12년 라이' WHERE name = 'Michter''s 12 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 15년 라이' WHERE name = 'Michter''s 15 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 18년 라이' WHERE name = 'Michter''s 18 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 20년 라이' WHERE name = 'Michter''s 20 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 25년 라이' WHERE name = 'Michter''s 25 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '믹터스 30년 라이' WHERE name = 'Michter''s 30 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '불릿 라이' WHERE name = 'Bulleit Rye Whiskey';
UPDATE whisky_note.catalog SET name_ko = '불릿 라이 10년' WHERE name = 'Bulleit Rye 10 Year';
UPDATE whisky_note.catalog SET name_ko = '불릿 라이 배럴 프루프' WHERE name = 'Bulleit Rye Barrel Proof';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 라이' WHERE name = 'Knob Creek Rye Whiskey';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 라이 12년' WHERE name = 'Knob Creek Rye 12 Year';
UPDATE whisky_note.catalog SET name_ko = '놉 크릭 라이 싱글 배럴' WHERE name = 'Knob Creek Rye Single Barrel';
UPDATE whisky_note.catalog SET name_ko = '하이 웨스트 더블 라이' WHERE name = 'High West Double Rye';
UPDATE whisky_note.catalog SET name_ko = '하이 웨스트 랑데부 라이' WHERE name = 'High West Rendezvous Rye';
UPDATE whisky_note.catalog SET name_ko = '하이 웨스트 라이' WHERE name = 'High West Rye';
UPDATE whisky_note.catalog SET name_ko = '올드 오버홀트 라이' WHERE name = 'Old Overholt Rye Whiskey';
UPDATE whisky_note.catalog SET name_ko = '올드 오버홀트 8년 라이' WHERE name = 'Old Overholt 8 Year Rye';
UPDATE whisky_note.catalog SET name_ko = '올드 오버홀트 라이 100 프루프' WHERE name = 'Old Overholt Rye 100 Proof';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 올드 No. 7' WHERE name = 'Jack Daniel''s Old No. 7';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 젠틀맨 잭' WHERE name = 'Jack Daniel''s Gentleman Jack';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 싱글 배럴 셀렉트' WHERE name = 'Jack Daniel''s Single Barrel Select';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 테네시 허니' WHERE name = 'Jack Daniel''s Tennessee Honey';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 테네시 파이어' WHERE name = 'Jack Daniel''s Tennessee Fire';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 싱글 배럴 라이' WHERE name = 'Jack Daniel''s Single Barrel Rye';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 12년 테네시 위스키' WHERE name = 'Jack Daniel''s 12 Year Old Tennessee Whiskey';
UPDATE whisky_note.catalog SET name_ko = '잭 다니엘 18년 테네시 위스키' WHERE name = 'Jack Daniel''s 18 Year Old Tennessee Whiskey';
UPDATE whisky_note.catalog SET name_ko = '조지 디켈 No. 8' WHERE name = 'George Dickel No. 8';
UPDATE whisky_note.catalog SET name_ko = '조지 디켈 No. 12' WHERE name = 'George Dickel No. 12';
UPDATE whisky_note.catalog SET name_ko = '조지 디켈 배럴 셀렉트' WHERE name = 'George Dickel Barrel Select';
UPDATE whisky_note.catalog SET name_ko = '조지 디켈 라이' WHERE name = 'George Dickel Rye';
UPDATE whisky_note.catalog SET name_ko = '조지 디켈 12년' WHERE name = 'George Dickel 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '조지 디켈 15년' WHERE name = 'George Dickel 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '엉클 니어리스트 프리미엄' WHERE name = 'Uncle Nearest Premium Whiskey';
UPDATE whisky_note.catalog SET name_ko = '엉클 니어리스트 12년' WHERE name = 'Uncle Nearest 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '엉클 니어리스트 18년' WHERE name = 'Uncle Nearest 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '엉클 니어리스트 싱글 배럴' WHERE name = 'Uncle Nearest Single Barrel';
UPDATE whisky_note.catalog SET name_ko = '엉클 니어리스트 라이' WHERE name = 'Uncle Nearest Rye';
UPDATE whisky_note.catalog SET name_ko = '제임슨 오리지널 아이리시 위스키' WHERE name = 'Jameson Original Irish Whiskey';
UPDATE whisky_note.catalog SET name_ko = '제임슨 블랙 배럴 아이리시 위스키' WHERE name = 'Jameson Black Barrel Irish Whiskey';
UPDATE whisky_note.catalog SET name_ko = '제임슨 18년 싱글몰트 아이리시 위스키' WHERE name = 'Jameson 18 Year Old Single Malt Irish Whiskey';
UPDATE whisky_note.catalog SET name_ko = '제임슨 캐스크메이츠 스타우트 에디션' WHERE name = 'Jameson Caskmates Stout Edition';
UPDATE whisky_note.catalog SET name_ko = '부시밀즈 오리지널 아이리시 위스키' WHERE name = 'Bushmills Original Irish Whiskey';
UPDATE whisky_note.catalog SET name_ko = '부시밀즈 블랙 부시 아이리시 위스키' WHERE name = 'Bushmills Black Bush Irish Whiskey';
UPDATE whisky_note.catalog SET name_ko = '부시밀즈 10년 싱글몰트' WHERE name = 'Bushmills 10 Year Old Single Malt';
UPDATE whisky_note.catalog SET name_ko = '부시밀즈 21년 싱글몰트' WHERE name = 'Bushmills 21 Year Old Single Malt';
UPDATE whisky_note.catalog SET name_ko = '부시밀즈 16년 캐스크 스트렝스' WHERE name = 'Bushmills 16 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '털러모어 듀 오리지널 아이리시 위스키' WHERE name = 'Tullamore D.E.W. Original Irish Whiskey';
UPDATE whisky_note.catalog SET name_ko = '털러모어 듀 12년 싱글몰트' WHERE name = 'Tullamore D.E.W. 12 Year Old Single Malt';
UPDATE whisky_note.catalog SET name_ko = '털러모어 듀 14년 싱글몰트' WHERE name = 'Tullamore D.E.W. 14 Year Old Single Malt';
UPDATE whisky_note.catalog SET name_ko = '털러모어 듀 캐스크 스트렝스 아이리시 위스키' WHERE name = 'Tullamore D.E.W. Cask Strength Irish Whiskey';
UPDATE whisky_note.catalog SET name_ko = '털러모어 듀 스페셜 리저브' WHERE name = 'Tullamore D.E.W. Special Reserve';
UPDATE whisky_note.catalog SET name_ko = '레드브레스트 12년' WHERE name = 'Redbreast 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레드브레스트 15년' WHERE name = 'Redbreast 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레드브레스트 21년' WHERE name = 'Redbreast 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '레드브레스트 12년 캐스크 스트렝스' WHERE name = 'Redbreast 12 Year Old Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '레드브레스트 루스타우' WHERE name = 'Redbreast Lustau';
UPDATE whisky_note.catalog SET name_ko = '그린 스팟' WHERE name = 'Green Spot';
UPDATE whisky_note.catalog SET name_ko = '그린 스팟 12년' WHERE name = 'Green Spot 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '그린 스팟 21년' WHERE name = 'Green Spot 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '그린 스팟 샤토 레오빌 바르통' WHERE name = 'Green Spot Château Léoville Barton';
UPDATE whisky_note.catalog SET name_ko = '그린 스팟 30년' WHERE name = 'Green Spot 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '옐로 스팟 12년' WHERE name = 'Yellow Spot 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '옐로 스팟 15년' WHERE name = 'Yellow Spot 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '옐로 스팟 18년' WHERE name = 'Yellow Spot 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '옐로 스팟 21년' WHERE name = 'Yellow Spot 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '옐로 스팟 30년' WHERE name = 'Yellow Spot 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '파워스 골드 라벨' WHERE name = 'Powers Gold Label';
UPDATE whisky_note.catalog SET name_ko = '파워스 존스 레인 12년' WHERE name = 'Powers John’s Lane Release 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '파워스 시그니처' WHERE name = 'Powers Signature';
UPDATE whisky_note.catalog SET name_ko = '파워스 15년' WHERE name = 'Powers 15 Year Old';
UPDATE whisky_note.catalog SET name_ko = '파워스 18년' WHERE name = 'Powers 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '미들턴 베리 레어' WHERE name = 'Midleton Very Rare';
UPDATE whisky_note.catalog SET name_ko = '미들턴 베리 레어 2015' WHERE name = 'Midleton Very Rare 2015';
UPDATE whisky_note.catalog SET name_ko = '미들턴 베리 레어 2018' WHERE name = 'Midleton Very Rare 2018';
UPDATE whisky_note.catalog SET name_ko = '미들턴 베리 레어 2020' WHERE name = 'Midleton Very Rare 2020';
UPDATE whisky_note.catalog SET name_ko = '미들턴 베리 레어 2022' WHERE name = 'Midleton Very Rare 2022';
UPDATE whisky_note.catalog SET name_ko = '틸링 스몰 배치' WHERE name = 'Teeling Small Batch';
UPDATE whisky_note.catalog SET name_ko = '틸링 싱글 그레인' WHERE name = 'Teeling Single Grain';
UPDATE whisky_note.catalog SET name_ko = '틸링 24년' WHERE name = 'Teeling 24 Year Old';
UPDATE whisky_note.catalog SET name_ko = '틸링 배치 22' WHERE name = 'Teeling Batch 22';
UPDATE whisky_note.catalog SET name_ko = '코네마라 피티드 싱글몰트' WHERE name = 'Connemara Peated Single Malt';
UPDATE whisky_note.catalog SET name_ko = '코네마라 12년' WHERE name = 'Connemara 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '코네마라 피티드 16년' WHERE name = 'Connemara Peated 16 Year Old';
UPDATE whisky_note.catalog SET name_ko = '워터포드 싱글 그레인' WHERE name = 'Waterford Single Grain';
UPDATE whisky_note.catalog SET name_ko = '워터포드 12년 싱글몰트' WHERE name = 'Waterford 12 Year Old Single Malt';
UPDATE whisky_note.catalog SET name_ko = '워터포드 21년 싱글몰트' WHERE name = 'Waterford 21 Year Old Single Malt';
UPDATE whisky_note.catalog SET name_ko = '웨스트 코크 아이리시 싱글몰트' WHERE name = 'West Cork Irish Single Malt';
UPDATE whisky_note.catalog SET name_ko = '웨스트 코크 12년' WHERE name = 'West Cork 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '웨스트 코크 21년' WHERE name = 'West Cork 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '야마자키 12년' WHERE name = 'Yamazaki 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '야마자키 18년' WHERE name = 'Yamazaki 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '야마자키 25년' WHERE name = 'Yamazaki 25 Year Old';
UPDATE whisky_note.catalog SET name_ko = '야마자키 셰리 캐스크' WHERE name = 'Yamazaki Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '야마자키 디스틸러스 리저브' WHERE name = 'Yamazaki Distiller''s Reserve';
UPDATE whisky_note.catalog SET name_ko = '하쿠슈 12년' WHERE name = 'Hakushu 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '하쿠슈 18년' WHERE name = 'Hakushu 18 Year Old';
UPDATE whisky_note.catalog SET name_ko = '하쿠슈 디스틸러스 리저브' WHERE name = 'Hakushu Distiller''s Reserve';
UPDATE whisky_note.catalog SET name_ko = '하쿠슈 포레스트' WHERE name = 'Hakushu Forest';
UPDATE whisky_note.catalog SET name_ko = '히비키 하모니' WHERE name = 'Hibiki Harmony';
UPDATE whisky_note.catalog SET name_ko = '히비키 12년' WHERE name = 'Hibiki 12 Year Old';
UPDATE whisky_note.catalog SET name_ko = '히비키 17년' WHERE name = 'Hibiki 17 Year Old';
UPDATE whisky_note.catalog SET name_ko = '히비키 21년' WHERE name = 'Hibiki 21 Year Old';
UPDATE whisky_note.catalog SET name_ko = '히비키 30년' WHERE name = 'Hibiki 30 Year Old';
UPDATE whisky_note.catalog SET name_ko = '산토리 토키' WHERE name = 'Suntory Toki';
UPDATE whisky_note.catalog SET name_ko = '산토리 토키 미즈나라' WHERE name = 'Suntory Toki Mizunara';
UPDATE whisky_note.catalog SET name_ko = '산토리 토키 재패니즈 하모니' WHERE name = 'Suntory Toki Japanese Harmony';
UPDATE whisky_note.catalog SET name_ko = '치타' WHERE name = 'The Chita';
UPDATE whisky_note.catalog SET name_ko = '치타 미즈나라' WHERE name = 'The Chita Mizunara';
UPDATE whisky_note.catalog SET name_ko = '치타 그레인 위스키' WHERE name = 'The Chita Grain Whisky';
UPDATE whisky_note.catalog SET name_ko = '요이치 싱글몰트' WHERE name = 'Yoichi Single Malt';
UPDATE whisky_note.catalog SET name_ko = '요이치 10년' WHERE name = 'Yoichi 10 Year';
UPDATE whisky_note.catalog SET name_ko = '요이치 15년' WHERE name = 'Yoichi 15 Year';
UPDATE whisky_note.catalog SET name_ko = '요이치 피티드' WHERE name = 'Yoichi Peated';
UPDATE whisky_note.catalog SET name_ko = '요이치 셰리 캐스크' WHERE name = 'Yoichi Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '미야기쿄 싱글몰트' WHERE name = 'Miyagikyo Single Malt';
UPDATE whisky_note.catalog SET name_ko = '미야기쿄 10년' WHERE name = 'Miyagikyo 10 Year';
UPDATE whisky_note.catalog SET name_ko = '미야기쿄 15년' WHERE name = 'Miyagikyo 15 Year';
UPDATE whisky_note.catalog SET name_ko = '미야기쿄 셰리 캐스크' WHERE name = 'Miyagikyo Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '미야기쿄 피티드' WHERE name = 'Miyagikyo Peated';
UPDATE whisky_note.catalog SET name_ko = '프롬 더 배럴' WHERE name = 'From the Barrel';
UPDATE whisky_note.catalog SET name_ko = '커피 그레인' WHERE name = 'Coffey Grain';
UPDATE whisky_note.catalog SET name_ko = '타케츠루 퓨어 몰트' WHERE name = 'Taketsuru Pure Malt';
UPDATE whisky_note.catalog SET name_ko = '타케츠루 12년' WHERE name = 'Taketsuru 12 Year';
UPDATE whisky_note.catalog SET name_ko = '타케츠루 18년' WHERE name = 'Taketsuru 18 Year';
UPDATE whisky_note.catalog SET name_ko = '타케츠루 30년' WHERE name = 'Taketsuru 30 Year';
UPDATE whisky_note.catalog SET name_ko = '타케츠루 50년' WHERE name = 'Taketsuru 50 Year';
UPDATE whisky_note.catalog SET name_ko = '이치로즈 몰트 치치부 더 퍼스트' WHERE name = 'Ichiro''s Malt Chichibu The First';
UPDATE whisky_note.catalog SET name_ko = '이치로즈 몰트 치치부 더 퍼스트 피티드' WHERE name = 'Ichiro''s Malt Chichibu The First Peated';
UPDATE whisky_note.catalog SET name_ko = '이치로즈 몰트 치치부 더 퍼스트 셰리 캐스크' WHERE name = 'Ichiro''s Malt Chichibu The First Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '이치로즈 몰트 치치부 더 퍼스트 리미티드 에디션 2020' WHERE name = 'Ichiro''s Malt Chichibu The First Limited Edition 2020';
UPDATE whisky_note.catalog SET name_ko = '마르스 신슈 코마가타케 2020' WHERE name = 'Mars Shinshu Komagatake 2020';
UPDATE whisky_note.catalog SET name_ko = '마르스 신슈 코마가타케 2021 셰리 캐스크' WHERE name = 'Mars Shinshu Komagatake 2021 Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '마르스 신슈 코마가타케 2022 피티드' WHERE name = 'Mars Shinshu Komagatake 2022 Peated';
UPDATE whisky_note.catalog SET name_ko = '마르스 신슈 더 퍼스트 에디션' WHERE name = 'Mars Shinshu The First Edition';
UPDATE whisky_note.catalog SET name_ko = '아케시 싱글몰트 2018' WHERE name = 'Akkeshi Single Malt 2018';
UPDATE whisky_note.catalog SET name_ko = '아케시 싱글몰트 2020 셰리 캐스크' WHERE name = 'Akkeshi Single Malt 2020 Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '아케시 싱글몰트 2021 피티드' WHERE name = 'Akkeshi Single Malt 2021 Peated';
UPDATE whisky_note.catalog SET name_ko = '아케시 리미티드 에디션 2022' WHERE name = 'Akkeshi Limited Edition 2022';
UPDATE whisky_note.catalog SET name_ko = '카노스케 싱글몰트 2019' WHERE name = 'Kanosuke Single Malt 2019';
UPDATE whisky_note.catalog SET name_ko = '카노스케 싱글몰트 2020 셰리 캐스크' WHERE name = 'Kanosuke Single Malt 2020 Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '카노스케 싱글몰트 2021 피티드' WHERE name = 'Kanosuke Single Malt 2021 Peated';
UPDATE whisky_note.catalog SET name_ko = '카노스케 리미티드 에디션 2022' WHERE name = 'Kanosuke Limited Edition 2022';
UPDATE whisky_note.catalog SET name_ko = '카발란 솔리스트 비뉴 바리크' WHERE name = 'Kavalan Solist Vinho Barrique';
UPDATE whisky_note.catalog SET name_ko = '카발란 솔리스트 셰리 캐스크' WHERE name = 'Kavalan Solist Sherry Cask';
UPDATE whisky_note.catalog SET name_ko = '카발란 솔리스트 포트 캐스크' WHERE name = 'Kavalan Solist Port Cask';
UPDATE whisky_note.catalog SET name_ko = '카발란 솔리스트 럼 캐스크 피니시' WHERE name = 'Kavalan Solist Rum Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '카발란 클래식 싱글몰트' WHERE name = 'Kavalan Classic Single Malt';
UPDATE whisky_note.catalog SET name_ko = '카발란 싱글 캐스크 2013' WHERE name = 'Kavalan Single Cask 2013';
UPDATE whisky_note.catalog SET name_ko = '오마 5년 싱글몰트' WHERE name = 'Omar 5 Year Single Malt';
UPDATE whisky_note.catalog SET name_ko = '오마 8년 싱글몰트' WHERE name = 'Omar 8 Year Single Malt';
UPDATE whisky_note.catalog SET name_ko = '오마 12년 싱글몰트' WHERE name = 'Omar 12 Year Single Malt';
UPDATE whisky_note.catalog SET name_ko = '오마 18년 싱글몰트' WHERE name = 'Omar 18 Year Single Malt';
UPDATE whisky_note.catalog SET name_ko = '오마 25년 싱글몰트' WHERE name = 'Omar 25 Year Single Malt';
UPDATE whisky_note.catalog SET name_ko = '오마 캐스크 스트렝스' WHERE name = 'Omar Cask Strength';
UPDATE whisky_note.catalog SET name_ko = '오마 셰리 캐스크 피니시' WHERE name = 'Omar Sherry Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '오마 포트 캐스크 피니시' WHERE name = 'Omar Port Cask Finish';
UPDATE whisky_note.catalog SET name_ko = '암룻 퓨전 싱글몰트' WHERE name = 'Amrut Fusion Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '암룻 싱글몰트 10년' WHERE name = 'Amrut Single Malt Whisky 10 Year';
UPDATE whisky_note.catalog SET name_ko = '암룻 포트 우드 피니시' WHERE name = 'Amrut Port Wood Finish';
UPDATE whisky_note.catalog SET name_ko = '암룻 피티드 싱글몰트' WHERE name = 'Amrut Peated Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '암룻 18년 싱글몰트' WHERE name = 'Amrut 18 Year Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '폴 존 싱글몰트 10년' WHERE name = 'Paul John Single Malt Whisky 10 Year';
UPDATE whisky_note.catalog SET name_ko = '폴 존 에디티드 (NAS) 싱글몰트' WHERE name = 'Paul John Edited (NAS) Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '폴 존 피티드 싱글몰트' WHERE name = 'Paul John Peated Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '폴 존 12년 싱글몰트' WHERE name = 'Paul John 12 Year Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '폴 존 싱글 캐스크 2015' WHERE name = 'Paul John Single Cask 2015';
UPDATE whisky_note.catalog SET name_ko = '람푸르 인디안 싱글몰트 12년' WHERE name = 'Rampur Indian Single Malt Whisky 12 Year';
UPDATE whisky_note.catalog SET name_ko = '람푸르 싱글 캐스크 (NAS) 싱글몰트' WHERE name = 'Rampur Single Cask (NAS) Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '람푸르 18년 싱글몰트' WHERE name = 'Rampur 18 Year Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '람푸르 25년 싱글몰트' WHERE name = 'Rampur 25 Year Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '람푸르 30년 싱글몰트' WHERE name = 'Rampur 30 Year Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '인드리 싱글몰트 12년' WHERE name = 'Indri Single Malt Whisky 12 Year';
UPDATE whisky_note.catalog SET name_ko = '인드리 피티드 싱글몰트 (NAS)' WHERE name = 'Indri Peated Single Malt Whisky (NAS)';
UPDATE whisky_note.catalog SET name_ko = '인드리 18년 싱글몰트' WHERE name = 'Indri 18 Year Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '인드리 싱글 캐스크 (NAS) 싱글몰트' WHERE name = 'Indri Single Cask (NAS) Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '인드리 25년 싱글몰트' WHERE name = 'Indri 25 Year Single Malt Whisky';
UPDATE whisky_note.catalog SET name_ko = '스타워드 노바' WHERE name = 'Starward Nova';
UPDATE whisky_note.catalog SET name_ko = '스타워드 10년' WHERE name = 'Starward 10 Year';
UPDATE whisky_note.catalog SET name_ko = '스타워드 12년' WHERE name = 'Starward 12 Year';
UPDATE whisky_note.catalog SET name_ko = '스타워드 15년' WHERE name = 'Starward 15 Year';
UPDATE whisky_note.catalog SET name_ko = '스타워드 18년' WHERE name = 'Starward 18 Year';
UPDATE whisky_note.catalog SET name_ko = '스타워드 30년' WHERE name = 'Starward 30 Year';
UPDATE whisky_note.catalog SET name_ko = '설리반스 코브 프렌치 오크' WHERE name = 'Sullivans Cove French Oak';
UPDATE whisky_note.catalog SET name_ko = '설리반스 코브 12년' WHERE name = 'Sullivans Cove 12 Year';
UPDATE whisky_note.catalog SET name_ko = '설리반스 코브 15년' WHERE name = 'Sullivans Cove 15 Year';
UPDATE whisky_note.catalog SET name_ko = '설리반스 코브 18년' WHERE name = 'Sullivans Cove 18 Year';
UPDATE whisky_note.catalog SET name_ko = '설리반스 코브 21년' WHERE name = 'Sullivans Cove 21 Year';
UPDATE whisky_note.catalog SET name_ko = '설리반스 코브 30년' WHERE name = 'Sullivans Cove 30 Year';
UPDATE whisky_note.catalog SET name_ko = '펜더린 싱글몰트' WHERE name = 'Penderyn Single Malt';
UPDATE whisky_note.catalog SET name_ko = '펜더린 10년' WHERE name = 'Penderyn 10 Year';
UPDATE whisky_note.catalog SET name_ko = '펜더린 12년' WHERE name = 'Penderyn 12 Year';
UPDATE whisky_note.catalog SET name_ko = '펜더린 15년' WHERE name = 'Penderyn 15 Year';
UPDATE whisky_note.catalog SET name_ko = '펜더린 피티드' WHERE name = 'Penderyn Peated';
UPDATE whisky_note.catalog SET name_ko = '펜더린 셰리 피니시' WHERE name = 'Penderyn Sherry Finish';
UPDATE whisky_note.catalog SET name_ko = '코츠월즈 싱글몰트' WHERE name = 'Cotswolds Single Malt';
UPDATE whisky_note.catalog SET name_ko = '코츠월즈 12년' WHERE name = 'Cotswolds 12 Year';
UPDATE whisky_note.catalog SET name_ko = '코츠월즈 15년' WHERE name = 'Cotswolds 15 Year';
UPDATE whisky_note.catalog SET name_ko = '코츠월즈 21년' WHERE name = 'Cotswolds 21 Year';
UPDATE whisky_note.catalog SET name_ko = '코츠월즈 30년' WHERE name = 'Cotswolds 30 Year';
UPDATE whisky_note.catalog SET name_ko = '밀크 앤 허니 싱글몰트' WHERE name = 'Milk & Honey Single Malt';
UPDATE whisky_note.catalog SET name_ko = '밀크 앤 허니 10년' WHERE name = 'Milk & Honey 10 Year';
UPDATE whisky_note.catalog SET name_ko = '밀크 앤 허니 12년' WHERE name = 'Milk & Honey 12 Year';
UPDATE whisky_note.catalog SET name_ko = '밀크 앤 허니 15년' WHERE name = 'Milk & Honey 15 Year';
UPDATE whisky_note.catalog SET name_ko = '밀크 앤 허니 18년' WHERE name = 'Milk & Honey 18 Year';
UPDATE whisky_note.catalog SET name_ko = '밀크 앤 허니 21년' WHERE name = 'Milk & Honey 21 Year';
UPDATE whisky_note.catalog SET name_ko = '마크미라 스벤스크 에크' WHERE name = 'Mackmyra Svensk Ek';
UPDATE whisky_note.catalog SET name_ko = '마크미라 5년' WHERE name = 'Mackmyra 5 Year';
UPDATE whisky_note.catalog SET name_ko = '마크미라 10년' WHERE name = 'Mackmyra 10 Year';
UPDATE whisky_note.catalog SET name_ko = '마크미라 12년' WHERE name = 'Mackmyra 12 Year';
UPDATE whisky_note.catalog SET name_ko = '마크미라 15년' WHERE name = 'Mackmyra 15 Year';
UPDATE whisky_note.catalog SET name_ko = '마크미라 18년' WHERE name = 'Mackmyra 18 Year';
UPDATE whisky_note.catalog SET name_ko = '마크미라 21년' WHERE name = 'Mackmyra 21 Year';
UPDATE whisky_note.catalog SET name_ko = '마크미라 30년' WHERE name = 'Mackmyra 30 Year';
UPDATE whisky_note.catalog SET name_ko = '크라운 로열' WHERE name = 'Crown Royal';
UPDATE whisky_note.catalog SET name_ko = '크라운 로열 XR' WHERE name = 'Crown Royal XR';
UPDATE whisky_note.catalog SET name_ko = '크라운 로열 리저브' WHERE name = 'Crown Royal Reserve';
UPDATE whisky_note.catalog SET name_ko = '캐나디안 클럽 100% 라이' WHERE name = 'Canadian Club 100% Rye';
UPDATE whisky_note.catalog SET name_ko = '캐나디안 클럽 12년' WHERE name = 'Canadian Club 12 Year';
UPDATE whisky_note.catalog SET name_ko = '캐나디안 클럽 30주년' WHERE name = 'Canadian Club 30th Anniversary';
UPDATE whisky_note.catalog SET name_ko = '로트 No. 40' WHERE name = 'Lot No. 40';
UPDATE whisky_note.catalog SET name_ko = '로트 No. 40 라이' WHERE name = 'Lot No. 40 Rye';
UPDATE whisky_note.catalog SET name_ko = '로트 No. 40 12년' WHERE name = 'Lot No. 40 12 Year';
