-- 글로벌 위스키 카탈로그 시드 (scripts/generate-catalog.mjs 생성, 901종)
-- AI 생성 데이터이므로 개별 수치(도수 등)에 오류가 있을 수 있다. 발견 시 이 파일이 아니라
-- 새 마이그레이션으로 수정할 것.

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Glenfiddich 12 Year Old', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번'),
('Glenfiddich 15 Year Old Solera Reserve', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 40.8, 15, '버번'),
('Glenfiddich 18 Year Old', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 40, 18, '버번'),
('Glenfiddich 21 Year Old Reserva Rum Cask Finish', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '럼'),
('Glenfiddich 30 Year Old', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, '버번'),
('Glenfiddich 12 Year Old Solera', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번'),
('Glenfiddich 18 Year Old Rare Oak', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번'),
('Glenfiddich Project XX', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, NULL),
('Glenfiddich 50 Year Old', 'Glenfiddich', 'single_malt', '스페이사이드', '스코틀랜드', 45, 50, '버번'),
('The Balvenie DoubleWood 12 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번'),
('The Balvenie DoubleWood 14 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 14, '버번'),
('The Balvenie DoubleWood 21 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번'),
('The Balvenie Caribbean Cask 14 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 14, '럼'),
('The Balvenie PortWood 21 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '포트'),
('The Balvenie Tun 1509 Batch 6', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, '버번'),
('The Balvenie 30 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, '버번'),
('The Balvenie 35 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 35, '버번'),
('The Balvenie 40 Year Old', 'The Balvenie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 40, '버번'),
('Kininvie 12 Year Old', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번'),
('Kininvie 15 Year Old', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, '버번'),
('Kininvie 18 Year Old', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번'),
('Kininvie 21 Year Old', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번'),
('Kininvie 30 Year Old', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, '버번'),
('Kininvie 12 Year Old Sherry Cask Finish', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '셰리'),
('Kininvie 12 Year Old Port Cask Finish', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '포트'),
('Kininvie 12 Year Old Cask Strength', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, '버번'),
('Kininvie 12 Year Old Single Cask', 'Kininvie', 'single_malt', '스페이사이드', '스코틀랜드', 45, 12, '버번'),
('The Macallan Sherry Oak 12 Year Old', 'The Macallan', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('The Macallan Double Cask 18 Year Old', 'The Macallan', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번·셰리'),
('The Macallan Rare Cask Black 2022', 'The Macallan', 'single_malt', '스페이사이드', '스코틀랜드', 43.2, NULL, '버번·셰리·포트'),
('The Macallan Edition No. 6 – The Red Collection', 'The Macallan', 'single_malt', '스페이사이드', '스코틀랜드', 43, NULL, '버번·셰리·포트·와인'),
('Aberlour 12 Year Old', 'Aberlour', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번·셰리'),
('Aberlour A''Bunadh', 'Aberlour', 'single_malt', '스페이사이드', '스코틀랜드', 60, NULL, '셰리'),
('Aberlour 21 Year Old', 'Aberlour', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번·셰리'),
('Aberlour 30 Year Old', 'Aberlour', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, '버번·셰리'),
('Cardhu 12 Year Old', 'Cardhu', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번·셰리'),
('Cardhu Gold Reserve', 'Cardhu', 'single_malt', '스페이사이드', '스코틀랜드', 43, NULL, '버번·셰리'),
('Cardhu 18 Year Old', 'Cardhu', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번·셰리'),
('Cardhu Limited Edition 2021 – The Glenlivet Collaboration', 'Cardhu', 'single_malt', '스페이사이드', '스코틀랜드', 43, NULL, '버번·셰리'),
('The Glenlivet 12 Year', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('The Glenlivet 15 Year', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('The Glenlivet 18 Year', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('The Glenlivet 21 Year', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, NULL),
('The Glenlivet Archive 21 Year', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번'),
('The Glenlivet Founder’s Reserve', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 46.5, NULL, '버번'),
('The Glenlivet Nadurra', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 46.5, NULL, '버번'),
('The Glenlivet 30 Year', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, NULL),
('The Glenlivet 12 Year Cask Strength', 'The Glenlivet', 'single_malt', '스페이사이드', '스코틀랜드', 55, 12, '버번'),
('Glen Grant 10 Year', 'Glen Grant', 'single_malt', '스페이사이드', '스코틀랜드', 40, 10, NULL),
('Glen Grant 12 Year', 'Glen Grant', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Glen Grant 15 Year', 'Glen Grant', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('Glen Grant 18 Year', 'Glen Grant', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('Glen Grant 21 Year', 'Glen Grant', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, NULL),
('Glen Grant Private Reserve', 'Glen Grant', 'single_malt', '스페이사이드', '스코틀랜드', 46.5, NULL, '버번'),
('Longmorn 12 Year', 'Longmorn', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Longmorn 18 Year', 'Longmorn', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('Longmorn 21 Year', 'Longmorn', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, NULL),
('Longmorn 25 Year', 'Longmorn', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, NULL),
('Longmorn 12 Year Cask Strength', 'Longmorn', 'single_malt', '스페이사이드', '스코틀랜드', 55, 12, '버번'),
('Glenfarclas 12 Year Old', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번'),
('Glenfarclas 15 Year Old', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, '버번'),
('Glenfarclas 18 Year Old', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번'),
('Glenfarclas 21 Year Old', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번'),
('Glenfarclas 25 Year Old', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, '버번'),
('Glenfarclas 30 Year Old', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, '버번'),
('Glenfarclas 40 Year Old', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 43, 40, '버번'),
('Glenfarclas 1990 (NAS)', 'Glenfarclas', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, '버번+셰리'),
('Craigellachie 12 Year Old', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '버번'),
('Craigellachie 13 Year Old', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 13, '버번'),
('Craigellachie 14 Year Old', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 14, '버번'),
('Craigellachie 16 Year Old', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 16, '버번'),
('Craigellachie 19 Year Old', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 19, '버번'),
('Craigellachie 25 Year Old', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, '버번'),
('Craigellachie 30 Year Old', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, '버번'),
('Craigellachie 1995 (NAS)', 'Craigellachie', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, '버번+셰리'),
('Aultmore 12 Year Old', 'Aultmore', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '버번'),
('Aultmore 15 Year Old', 'Aultmore', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, '버번'),
('Aultmore 18 Year Old', 'Aultmore', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번'),
('Aultmore 21 Year Old', 'Aultmore', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번'),
('Aultmore 25 Year Old', 'Aultmore', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, '버번'),
('Aultmore 30 Year Old', 'Aultmore', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, '버번'),
('Aultmore 1990 (NAS)', 'Aultmore', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, '버번+셰리'),
('Mortlach 12 Year Old', 'Mortlach', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Mortlach 16 Year Old', 'Mortlach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 16, NULL),
('Mortlach 21 Year Old', 'Mortlach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, NULL),
('Mortlach 25 Year Old', 'Mortlach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, NULL),
('Mortlach 30 Year Old', 'Mortlach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, NULL),
('Mortlach 12 Year Old Sherry Cask', 'Mortlach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Mortlach 12 Year Old Bourbon Cask', 'Mortlach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '버번'),
('The Singleton of Dufftown 12 Year Old', 'The Singleton of Dufftown', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('The Singleton of Dufftown 15 Year Old', 'The Singleton of Dufftown', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('The Singleton of Dufftown 18 Year Old', 'The Singleton of Dufftown', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('The Singleton of Dufftown 12 Year Old Sherry Cask', 'The Singleton of Dufftown', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('The Singleton of Dufftown 12 Year Old Port Cask', 'The Singleton of Dufftown', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '포트'),
('Glendullan 12 Year Old', 'Glendullan', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Glendullan 15 Year Old', 'Glendullan', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('Glendullan 18 Year Old', 'Glendullan', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('Glendullan 12 Year Old Sherry Cask', 'Glendullan', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Glendullan 12 Year Old Port Cask', 'Glendullan', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '포트'),
('Glendullan 12 Year Old Rum Cask', 'Glendullan', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '럼')
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('BenRiach 10 Year Old', 'BenRiach', 'single_malt', '스페이사이드', '스코틀랜드', 40, 10, NULL),
('BenRiach 12 Year Old', 'BenRiach', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('BenRiach 21 Year Old', 'BenRiach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, NULL),
('BenRiach 25 Year Old', 'BenRiach', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, NULL),
('BenRiach Peat Smoke', 'BenRiach', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, NULL),
('BenRiach 12 Year Old Sherry Cask', 'BenRiach', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '셰리'),
('BenRiach 12 Year Old Port Cask', 'BenRiach', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '포트'),
('Glen Moray 10 Year Old', 'Glen Moray', 'single_malt', '스페이사이드', '스코틀랜드', 40, 10, NULL),
('Glen Moray 12 Year Old', 'Glen Moray', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Glen Moray 15 Year Old', 'Glen Moray', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('Glen Moray 18 Year Old', 'Glen Moray', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('Glen Moray 21 Year Old', 'Glen Moray', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, NULL),
('Glen Moray 30 Year Old', 'Glen Moray', 'single_malt', '스페이사이드', '스코틀랜드', 43, 30, NULL),
('Glen Moray Legacy', 'Glen Moray', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, NULL),
('Speyburn 10 Year Old', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 40, 10, NULL),
('Speyburn 12 Year Old', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Speyburn 15 Year Old', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('Speyburn 18 Year Old', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('Speyburn 21 Year Old', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, NULL),
('Speyburn 25 Year Old', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, NULL),
('Speyburn 12 Year Old Sherry Cask', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '셰리'),
('Speyburn 12 Year Old Port Cask', 'Speyburn', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, '포트'),
('Benromach 10 Year Old', 'Benromach', 'single_malt', '스페이사이드', '스코틀랜드', 46, 10, '버번'),
('Benromach 12 Year Old', 'Benromach', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, '버번'),
('Benromach Peat Smoke', 'Benromach', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, NULL),
('Benromach Batch 1', 'Benromach', 'single_malt', '스페이사이드', '스코틀랜드', 58, NULL, NULL),
('Benromach 25 Year Old', 'Benromach', 'single_malt', '스페이사이드', '스코틀랜드', 46, 25, '셰리'),
('The Glenrothes 12 Year Old', 'The Glenrothes', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '버번'),
('The Glenrothes 18 Year Old', 'The Glenrothes', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번'),
('The Glenrothes 21 Year Old', 'The Glenrothes', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번'),
('The Glenrothes 25 Year Old', 'The Glenrothes', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, '버번'),
('The Glenrothes Select', 'The Glenrothes', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, NULL),
('Glen Elgin 12 Year Old', 'Glen Elgin', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '버번'),
('Glen Elgin 15 Year Old', 'Glen Elgin', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, '버번'),
('Glen Elgin 18 Year Old', 'Glen Elgin', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, '버번'),
('Glen Elgin 21 Year Old', 'Glen Elgin', 'single_malt', '스페이사이드', '스코틀랜드', 43, 21, '버번'),
('Glen Elgin 12 Year Old Sherry Cask', 'Glen Elgin', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Glen Elgin 12 Year Old Port Cask', 'Glen Elgin', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '포트'),
('Strathisla 12 Year Old', 'Strathisla', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Strathisla 18 Year Old', 'Strathisla', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('Strathisla 25 Year Old', 'Strathisla', 'single_malt', '스페이사이드', '스코틀랜드', 43, 25, NULL),
('Strathisla 12 Year Old Cask Strength', 'Strathisla', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, NULL),
('Strathisla 12 Year Old Sherry Cask', 'Strathisla', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Strathisla 12 Year Old Port Cask', 'Strathisla', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '포트'),
('Tamdhu 10 Year Old', 'Tamdhu', 'single_malt', '스페이사이드', '스코틀랜드', 40, 10, NULL),
('Tamdhu 12 Year Old', 'Tamdhu', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, NULL),
('Tamdhu 15 Year Old', 'Tamdhu', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('Tamdhu 12 Year Old Cask Strength', 'Tamdhu', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, NULL),
('Tamdhu 12 Year Old Sherry Cask', 'Tamdhu', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Tamdhu 10 Year Old Port Cask', 'Tamdhu', 'single_malt', '스페이사이드', '스코틀랜드', 43, 10, '포트'),
('Knockando 12 Year Old', 'Knockando', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Knockando 15 Year Old', 'Knockando', 'single_malt', '스페이사이드', '스코틀랜드', 43, 15, NULL),
('Knockando 18 Year Old', 'Knockando', 'single_malt', '스페이사이드', '스코틀랜드', 43, 18, NULL),
('Knockando 12 Year Old Cask Strength', 'Knockando', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, NULL),
('Knockando 12 Year Old Sherry Cask', 'Knockando', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Knockando 12 Year Old Port Cask', 'Knockando', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '포트'),
('Linkwood 12 Year', 'Linkwood', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Linkwood 18 Year', 'Linkwood', 'single_malt', '스페이사이드', '스코틀랜드', 40, 18, NULL),
('Linkwood 12 Year Cask Strength', 'Linkwood', 'single_malt', '스페이사이드', '스코틀랜드', 58, 12, '버번'),
('Linkwood 12 Year Sherry Cask', 'Linkwood', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Tormore 12 Year', 'Tormore', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Tormore 14 Year', 'Tormore', 'single_malt', '스페이사이드', '스코틀랜드', 40, 14, NULL),
('Tormore 12 Year Cask Strength', 'Tormore', 'single_malt', '스페이사이드', '스코틀랜드', 57, 12, '버번'),
('Tormore 12 Year Sherry Cask', 'Tormore', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Glentauchers 12 Year', 'Glentauchers', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Glentauchers 18 Year', 'Glentauchers', 'single_malt', '스페이사이드', '스코틀랜드', 40, 18, NULL),
('Glentauchers 12 Year Sherry Cask', 'Glentauchers', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Glentauchers 12 Year Cask Strength', 'Glentauchers', 'single_malt', '스페이사이드', '스코틀랜드', 56, 12, '버번'),
('Tamnavulin 10 Year', 'Tamnavulin', 'single_malt', '스페이사이드', '스코틀랜드', 40, 10, NULL),
('Tamnavulin 12 Year', 'Tamnavulin', 'single_malt', '스페이사이드', '스코틀랜드', 40, 12, NULL),
('Tamnavulin 12 Year Sherry Cask', 'Tamnavulin', 'single_malt', '스페이사이드', '스코틀랜드', 43, 12, '셰리'),
('Tamnavulin 12 Year Cask Strength', 'Tamnavulin', 'single_malt', '스페이사이드', '스코틀랜드', 57, 12, '버번'),
('Cragganmore 12 Year Old', 'Cragganmore', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, '버번'),
('Cragganmore 15 Year Old', 'Cragganmore', 'single_malt', '스페이사이드', '스코틀랜드', 46, 15, '버번'),
('Cragganmore 18 Year Old', 'Cragganmore', 'single_malt', '스페이사이드', '스코틀랜드', 46, 18, '버번'),
('Cragganmore 25 Year Old', 'Cragganmore', 'single_malt', '스페이사이드', '스코틀랜드', 46, 25, '버번'),
('Cragganmore Cask Strength', 'Cragganmore', 'single_malt', '스페이사이드', '스코틀랜드', 58, NULL, NULL),
('Dailuaine 12 Year Old', 'Dailuaine', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, '버번'),
('Dailuaine 15 Year Old', 'Dailuaine', 'single_malt', '스페이사이드', '스코틀랜드', 46, 15, '버번'),
('Dailuaine 18 Year Old', 'Dailuaine', 'single_malt', '스페이사이드', '스코틀랜드', 46, 18, '버번'),
('Dailuaine 21 Year Old', 'Dailuaine', 'single_malt', '스페이사이드', '스코틀랜드', 46, 21, '버번'),
('Dailuaine Port Wood Finish', 'Dailuaine', 'single_malt', '스페이사이드', '스코틀랜드', 46, NULL, '포트'),
('Inchgower 12 Year Old', 'Inchgower', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, '버번'),
('Inchgower 15 Year Old', 'Inchgower', 'single_malt', '스페이사이드', '스코틀랜드', 46, 15, '버번'),
('Inchgower 18 Year Old', 'Inchgower', 'single_malt', '스페이사이드', '스코틀랜드', 46, 18, '버번'),
('Inchgower 21 Year Old', 'Inchgower', 'single_malt', '스페이사이드', '스코틀랜드', 46, 21, '버번'),
('Inchgower Cask Strength', 'Inchgower', 'single_malt', '스페이사이드', '스코틀랜드', 58, NULL, NULL),
('Ballindalloch 12 Year Old', 'Ballindalloch', 'single_malt', '스페이사이드', '스코틀랜드', 46, 12, '버번'),
('Ballindalloch 15 Year Old', 'Ballindalloch', 'single_malt', '스페이사이드', '스코틀랜드', 46, 15, '버번'),
('Ballindalloch 18 Year Old', 'Ballindalloch', 'single_malt', '스페이사이드', '스코틀랜드', 46, 18, '버번'),
('Ballindalloch 21 Year Old', 'Ballindalloch', 'single_malt', '스페이사이드', '스코틀랜드', 46, 21, '버번'),
('Ballindalloch Cask Strength', 'Ballindalloch', 'single_malt', '스페이사이드', '스코틀랜드', 58, NULL, NULL),
('Glenmorangie Original 10 Year Old', 'Glenmorangie', 'single_malt', '하이랜드', '스코틀랜드', 40, 10, '버번'),
('Glenmorangie Nectar d''Or', 'Glenmorangie', 'single_malt', '하이랜드', '스코틀랜드', 43, NULL, '버번 & 셰리'),
('Glenmorangie Lasanta 12 Year Old', 'Glenmorangie', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '셰리'),
('Glenmorangie Signet', 'Glenmorangie', 'single_malt', '하이랜드', '스코틀랜드', 46, NULL, '버번, 포트, 셰리'),
('Glenmorangie 18 Year Old', 'Glenmorangie', 'single_malt', '하이랜드', '스코틀랜드', 43, 18, '버번'),
('The Dalmore 12 Year Old', 'The Dalmore', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '버번'),
('The Dalmore 15 Year Old', 'The Dalmore', 'single_malt', '하이랜드', '스코틀랜드', 43, 15, '버번 & 셰리'),
('The Dalmore 18 Year Old', 'The Dalmore', 'single_malt', '하이랜드', '스코틀랜드', 43, 18, '버번 & 셰리')
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('The Dalmore King Alexander III', 'The Dalmore', 'single_malt', '하이랜드', '스코틀랜드', 43, NULL, '버번 & 셰리'),
('The Dalmore Cigar Malt', 'The Dalmore', 'single_malt', '하이랜드', '스코틀랜드', 46, NULL, '버번 & 셰리'),
('The GlenDronach 12 Year Old Original', 'The GlenDronach', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '셰리'),
('The GlenDronach 15 Year Old Revival', 'The GlenDronach', 'single_malt', '하이랜드', '스코틀랜드', 46, 15, '셰리'),
('The GlenDronach 18 Year Old Allardice', 'The GlenDronach', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, '셰리'),
('The GlenDronach 21 Year Old Parliament', 'The GlenDronach', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '셰리'),
('The GlenDronach 12 Year Old Cask Strength', 'The GlenDronach', 'single_malt', '하이랜드', '스코틀랜드', 58, 12, '셰리'),
('Oban 14 Year Old', 'Oban', 'single_malt', '하이랜드', '스코틀랜드', 43, 14, '버번/셰리'),
('Oban 18 Year Old', 'Oban', 'single_malt', '하이랜드', '스코틀랜드', 43, 18, '버번/셰리'),
('Oban 8 Year Old', 'Oban', 'single_malt', '하이랜드', '스코틀랜드', 43, 8, '버번'),
('Oban Little Bay', 'Oban', 'single_malt', '하이랜드', '스코틀랜드', 46.2, 12, '버번'),
('Oban Distillers Edition', 'Oban', 'single_malt', '하이랜드', '스코틀랜드', 46.2, 14, '버번/셰리'),
('Clynelish 14 Year Old', 'Clynelish', 'single_malt', '하이랜드', '스코틀랜드', 43, 14, '버번'),
('Clynelish 12 Year Old', 'Clynelish', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('Clynelish 18 Year Old', 'Clynelish', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, '버번'),
('Clynelish 25 Year Old', 'Clynelish', 'single_malt', '하이랜드', '스코틀랜드', 46, 25, '버번'),
('Clynelish 30 Year Old', 'Clynelish', 'single_malt', '하이랜드', '스코틀랜드', 46, 30, '버번'),
('Old Pulteney 12 Year Old', 'Old Pulteney', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('Old Pulteney 12 Year Old Port Wood Finish', 'Old Pulteney', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '포트'),
('Old Pulteney 12 Year Old Sherry Wood Finish', 'Old Pulteney', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '셰리'),
('Old Pulteney 18 Year Old', 'Old Pulteney', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, '버번'),
('Old Pulteney 21 Year Old', 'Old Pulteney', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '버번'),
('Dalwhinnie 12 Year', 'Dalwhinnie', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '버번'),
('Dalwhinnie 15 Year', 'Dalwhinnie', 'single_malt', '하이랜드', '스코틀랜드', 40, 15, '버번'),
('Dalwhinnie 18 Year', 'Dalwhinnie', 'single_malt', '하이랜드', '스코틀랜드', 40, 18, '버번'),
('Dalwhinnie 25 Year', 'Dalwhinnie', 'single_malt', '하이랜드', '스코틀랜드', 46, 25, '버번'),
('Dalwhinnie 30 Year', 'Dalwhinnie', 'single_malt', '하이랜드', '스코틀랜드', 46, 30, '버번'),
('Tomatin 12 Year', 'Tomatin', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('Tomatin 12 Year Sherry Cask', 'Tomatin', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '셰리'),
('Tomatin 12 Year Port Cask', 'Tomatin', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '포트'),
('Tomatin 18 Year', 'Tomatin', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, '버번'),
('Tomatin 21 Year', 'Tomatin', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '버번'),
('The Singleton Glen Ord 12 Year', 'The Singleton of Glen Ord', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '버번'),
('The Singleton Glen Ord 12 Year Sherry Cask', 'The Singleton of Glen Ord', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '셰리'),
('The Singleton Glen Ord 15 Year', 'The Singleton of Glen Ord', 'single_malt', '하이랜드', '스코틀랜드', 43, 15, '버번'),
('The Singleton Glen Ord 18 Year', 'The Singleton of Glen Ord', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, '버번'),
('The Singleton Glen Ord 21 Year', 'The Singleton of Glen Ord', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '버번'),
('Aberfeldy 12 Year Old', 'Aberfeldy', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '버번'),
('Aberfeldy 21 Year Old', 'Aberfeldy', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '셰리'),
('Aberfeldy 10 Year Old', 'Aberfeldy', 'single_malt', '하이랜드', '스코틀랜드', 40, 10, '버번'),
('Aberfeldy 30 Year Old', 'Aberfeldy', 'single_malt', '하이랜드', '스코틀랜드', 46, 30, '셰리'),
('Aberfeldy 1995 NAS', 'Aberfeldy', 'single_malt', '하이랜드', '스코틀랜드', NULL, NULL, NULL),
('Edradour 12 Year Old', 'Edradour', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '버번'),
('Edradour 15 Year Old', 'Edradour', 'single_malt', '하이랜드', '스코틀랜드', 46, 15, '버번'),
('Edradour 18 Year Old', 'Edradour', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, '버번'),
('Edradour 25 Year Old', 'Edradour', 'single_malt', '하이랜드', '스코틀랜드', 46, 25, '셰리'),
('Edradour 1999 NAS', 'Edradour', 'single_malt', '하이랜드', '스코틀랜드', NULL, NULL, NULL),
('Blair Athol 12 Year Old', 'Blair Athol', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '버번'),
('Blair Athol 15 Year Old', 'Blair Athol', 'single_malt', '하이랜드', '스코틀랜드', 40, 15, '버번'),
('Blair Athol 18 Year Old', 'Blair Athol', 'single_malt', '하이랜드', '스코틀랜드', 40, 18, '버번'),
('Blair Athol 21 Year Old', 'Blair Athol', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '셰리'),
('Blair Athol 1995 NAS', 'Blair Athol', 'single_malt', '하이랜드', '스코틀랜드', NULL, NULL, NULL),
('Glengoyne 10 Year Old', 'Glengoyne', 'single_malt', '하이랜드', '스코틀랜드', 43, 10, '버번'),
('Glengoyne 12 Year Old Sherry Cask', 'Glengoyne', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '셰리'),
('Glengoyne 21 Year Old', 'Glengoyne', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '버번'),
('Glengoyne 25 Year Old', 'Glengoyne', 'single_malt', '하이랜드', '스코틀랜드', 46, 25, '버번'),
('Deanston 12 Year Old', 'Deanston', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('Deanston 18 Year Old', 'Deanston', 'single_malt', '하이랜드', '스코틀랜드', 43, 18, '버번'),
('Deanston 21 Year Old Sherry Cask', 'Deanston', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '셰리'),
('Deanston 30 Year Old', 'Deanston', 'single_malt', '하이랜드', '스코틀랜드', 46, 30, '버번'),
('Tullibardine 12 Year Old', 'Tullibardine', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('Tullibardine 18 Year Old', 'Tullibardine', 'single_malt', '하이랜드', '스코틀랜드', 43, 18, '버번'),
('Tullibardine 21 Year Old Sherry Cask', 'Tullibardine', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, '셰리'),
('Tullibardine 30 Year Old', 'Tullibardine', 'single_malt', '하이랜드', '스코틀랜드', 46, 30, '버번'),
('Royal Lochnagar 12 Year', 'Royal Lochnagar', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, NULL),
('Royal Lochnagar 18 Year', 'Royal Lochnagar', 'single_malt', '하이랜드', '스코틀랜드', 40, 18, NULL),
('Royal Lochnagar 21 Year', 'Royal Lochnagar', 'single_malt', '하이랜드', '스코틀랜드', 40, 21, NULL),
('Royal Lochnagar 12 Year Sherry Cask', 'Royal Lochnagar', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '셰리'),
('Fettercairn 12 Year', 'Fettercairn', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, NULL),
('Fettercairn 21 Year', 'Fettercairn', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, NULL),
('Fettercairn 12 Year Sherry Cask', 'Fettercairn', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '셰리'),
('Fettercairn 12 Year Port Cask', 'Fettercairn', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '포트'),
('Glencadam 10 Year', 'Glencadam', 'single_malt', '하이랜드', '스코틀랜드', 40, 10, NULL),
('Glencadam 12 Year', 'Glencadam', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, NULL),
('Glencadam 18 Year', 'Glencadam', 'single_malt', '하이랜드', '스코틀랜드', 40, 18, NULL),
('Glencadam 12 Year Sherry Cask', 'Glencadam', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '셰리'),
('Glencadam 12 Year Port Cask', 'Glencadam', 'single_malt', '하이랜드', '스코틀랜드', 40, 12, '포트'),
('anCnoc 12 Year Old', 'anCnoc', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('anCnoc 14 Year Old', 'anCnoc', 'single_malt', '하이랜드', '스코틀랜드', 43, 14, '버번'),
('anCnoc 18 Year Old', 'anCnoc', 'single_malt', '하이랜드', '스코틀랜드', 43, 18, '버번'),
('anCnoc Peatheart', 'anCnoc', 'single_malt', '하이랜드', '스코틀랜드', 46, NULL, '버번'),
('Balblair 12 Year Old', 'Balblair', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('Balblair 15 Year Old', 'Balblair', 'single_malt', '하이랜드', '스코틀랜드', 43, 15, '버번'),
('Balblair 21 Year Old', 'Balblair', 'single_malt', '하이랜드', '스코틀랜드', 43, 21, '버번'),
('Balblair 30 Year Old', 'Balblair', 'single_malt', '하이랜드', '스코틀랜드', 43, 30, '버번'),
('Balblair 1990 Vintage', 'Balblair', 'single_malt', '하이랜드', '스코틀랜드', 46, NULL, '셰리'),
('Glen Garioch 12 Year Old', 'Glen Garioch', 'single_malt', '하이랜드', '스코틀랜드', 43, 12, '버번'),
('Glen Garioch 18 Year Old', 'Glen Garioch', 'single_malt', '하이랜드', '스코틀랜드', 43, 18, '버번'),
('Glen Garioch 21 Year Old', 'Glen Garioch', 'single_malt', '하이랜드', '스코틀랜드', 43, 21, '버번'),
('Glen Garioch 1990 Vintage', 'Glen Garioch', 'single_malt', '하이랜드', '스코틀랜드', 46, NULL, '셰리'),
('Glen Garioch 30 Year Old', 'Glen Garioch', 'single_malt', '하이랜드', '스코틀랜드', 43, 30, '버번'),
('Ardmore Legacy 12 Year Old', 'Ardmore', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '버번'),
('Ardmore Traditional 12 Year Old', 'Ardmore', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '버번'),
('Ardmore 10 Year Old', 'Ardmore', 'single_malt', '하이랜드', '스코틀랜드', 46, 10, NULL),
('Ardmore 18 Year Old', 'Ardmore', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, NULL),
('Ardmore 25 Year Old', 'Ardmore', 'single_malt', '하이랜드', '스코틀랜드', 46, 25, NULL),
('Loch Lomond Original', 'Loch Lomond', 'single_malt', '하이랜드', '스코틀랜드', 40, NULL, NULL),
('Loch Lomond 12 Year Old', 'Loch Lomond', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, NULL),
('Loch Lomond 18 Year Old', 'Loch Lomond', 'single_malt', '하이랜드', '스코틀랜드', 46, 18, NULL),
('Loch Lomond Triple Wood', 'Loch Lomond', 'single_malt', '하이랜드', '스코틀랜드', 46, NULL, NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Loch Lomond 12 Year Old Sherry Cask', 'Loch Lomond', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '셰리'),
('Wolfburn 12 Year Old', 'Wolfburn', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, NULL),
('Wolfburn 16 Year Old', 'Wolfburn', 'single_malt', '하이랜드', '스코틀랜드', 46, 16, NULL),
('Wolfburn 12 Year Old Sherry Cask', 'Wolfburn', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '셰리'),
('Wolfburn 12 Year Old Cask Strength', 'Wolfburn', 'single_malt', '하이랜드', '스코틀랜드', 58, 12, NULL),
('Glenglassaugh 12 Year Old', 'Glenglassaugh', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, NULL),
('Glenglassaugh 15 Year Old', 'Glenglassaugh', 'single_malt', '하이랜드', '스코틀랜드', 46, 15, NULL),
('Glenglassaugh 21 Year Old', 'Glenglassaugh', 'single_malt', '하이랜드', '스코틀랜드', 46, 21, NULL),
('Glenglassaugh 12 Year Old Sherry Cask', 'Glenglassaugh', 'single_malt', '하이랜드', '스코틀랜드', 46, 12, '셰리'),
('Glenglassaugh 12 Year Old Cask Strength', 'Glenglassaugh', 'single_malt', '하이랜드', '스코틀랜드', 58, 12, NULL),
('Ardbeg 10 Year', 'Ardbeg', 'single_malt', '아일라', '스코틀랜드', 46, 10, '버번'),
('Ardbeg Uigeadail', 'Ardbeg', 'single_malt', '아일라', '스코틀랜드', 54.2, 12, '버번·셰리'),
('Ardbeg Corryvreckan', 'Ardbeg', 'single_malt', '아일라', '스코틀랜드', 57.8, 12, '버번·포트'),
('Ardbeg An Oa', 'Ardbeg', 'single_malt', '아일라', '스코틀랜드', 53, 15, '버번·셰리'),
('Ardbeg Kelpie', 'Ardbeg', 'single_malt', '아일라', '스코틀랜드', 46, NULL, '버번'),
('Lagavulin 16 Year', 'Lagavulin', 'single_malt', '아일라', '스코틀랜드', 43, 16, '버번'),
('Lagavulin 12 Year', 'Lagavulin', 'single_malt', '아일라', '스코틀랜드', 43, 12, '버번'),
('Lagavulin Distillers Edition', 'Lagavulin', 'single_malt', '아일라', '스코틀랜드', 46, 12, '셰리'),
('Lagavulin 8 Year', 'Lagavulin', 'single_malt', '아일라', '스코틀랜드', 43, 8, '버번'),
('Lagavulin 12 Year Cask Strength', 'Lagavulin', 'single_malt', '아일라', '스코틀랜드', 55.2, 12, '버번'),
('Laphroaig 10 Year', 'Laphroaig', 'single_malt', '아일라', '스코틀랜드', 40, 10, '버번'),
('Laphroaig Quarter Cask', 'Laphroaig', 'single_malt', '아일라', '스코틀랜드', 48, 10, '버번'),
('Laphroaig Triple Wood', 'Laphroaig', 'single_malt', '아일라', '스코틀랜드', 43, 12, '버번·셰리·포트'),
('Laphroaig 12 Year', 'Laphroaig', 'single_malt', '아일라', '스코틀랜드', 43, 12, '버번'),
('Laphroaig Lore', 'Laphroaig', 'single_malt', '아일라', '스코틀랜드', 46, NULL, '버번'),
('Bowmore 12 Year Old', 'Bowmore', 'single_malt', '아일라', '스코틀랜드', 40, 12, '버번'),
('Bowmore 18 Year Old', 'Bowmore', 'single_malt', '아일라', '스코틀랜드', 43, 18, '버번'),
('Bowmore 25 Year Old', 'Bowmore', 'single_malt', '아일라', '스코틀랜드', 46, 25, '셰리'),
('Bowmore Darkest 2022', 'Bowmore', 'single_malt', '아일라', '스코틀랜드', 46, NULL, '버번'),
('Bruichladdich Classic Laddie', 'Bruichladdich', 'single_malt', '아일라', '스코틀랜드', 46, NULL, '버번'),
('Bruichladdich The Classic Laddie 12 Year Old', 'Bruichladdich', 'single_malt', '아일라', '스코틀랜드', 46, 12, '버번'),
('Bruichladdich Port Charlotte 12 Year Old', 'Bruichladdich', 'single_malt', '아일라', '스코틀랜드', 46, 12, '버번'),
('Bruichladdich Octomore 10.0', 'Bruichladdich', 'single_malt', '아일라', '스코틀랜드', 46.5, NULL, '버번'),
('Port Charlotte 12 Year Old', 'Port Charlotte', 'single_malt', '아일라', '스코틀랜드', 46, 12, '버번'),
('Port Charlotte 18 Year Old', 'Port Charlotte', 'single_malt', '아일라', '스코틀랜드', 46, 18, '버번'),
('Port Charlotte 30 Year Old', 'Port Charlotte', 'single_malt', '아일라', '스코틀랜드', 46, 30, '버번'),
('Octomore 12.1', 'Octomore', 'single_malt', '아일라', '스코틀랜드', 47, NULL, '버번'),
('Octomore 14.2', 'Octomore', 'single_malt', '아일라', '스코틀랜드', 48, NULL, '버번'),
('Octomore 16.1', 'Octomore', 'single_malt', '아일라', '스코틀랜드', 48.5, NULL, '버번'),
('Caol Ila 12 Year', 'Caol Ila', 'single_malt', '아일라', '스코틀랜드', 43, 12, '버번'),
('Caol Ila 18 Year', 'Caol Ila', 'single_malt', '아일라', '스코틀랜드', 46, 18, '버번'),
('Caol Ila 25 Year', 'Caol Ila', 'single_malt', '아일라', '스코틀랜드', 48, 25, '버번'),
('Caol Ila 12 Year Cask Strength', 'Caol Ila', 'single_malt', '아일라', '스코틀랜드', 58, 12, '버번'),
('Caol Ila 2021 Islay Single Malt', 'Caol Ila', 'single_malt', '아일라', '스코틀랜드', 55, NULL, '버번'),
('Bunnahabhain 12 Year', 'Bunnahabhain', 'single_malt', '아일라', '스코틀랜드', 43, 12, '버번'),
('Bunnahabhain 18 Year', 'Bunnahabhain', 'single_malt', '아일라', '스코틀랜드', 46, 18, '버번'),
('Bunnahabhain 21 Year', 'Bunnahabhain', 'single_malt', '아일라', '스코틀랜드', 46.5, 21, '버번'),
('Bunnahabhain 12 Year Cask Strength', 'Bunnahabhain', 'single_malt', '아일라', '스코틀랜드', 58, 12, '버번'),
('Bunnahabhain Toiteach', 'Bunnahabhain', 'single_malt', '아일라', '스코틀랜드', 45, NULL, '버번'),
('Kilchoman Machir Bay', 'Kilchoman', 'single_malt', '아일라', '스코틀랜드', 46, NULL, '버번'),
('Kilchoman 12 Year', 'Kilchoman', 'single_malt', '아일라', '스코틀랜드', 46.5, 12, '버번'),
('Kilchoman 15 Year', 'Kilchoman', 'single_malt', '아일라', '스코틀랜드', 48, 15, '버번'),
('Kilchoman 25 Year', 'Kilchoman', 'single_malt', '아일라', '스코틀랜드', 50, 25, '버번'),
('Kilchoman Machir Bay Cask Strength', 'Kilchoman', 'single_malt', '아일라', '스코틀랜드', 58, NULL, '버번'),
('Ardnahoe 10 Year', 'Ardnahoe', 'single_malt', '아일라', '스코틀랜드', 43, 10, '버번'),
('Ardnahoe 12 Year', 'Ardnahoe', 'single_malt', '아일라', '스코틀랜드', 45, 12, '버번'),
('Ardnahoe 18 Year', 'Ardnahoe', 'single_malt', '아일라', '스코틀랜드', 46.5, 18, '버번'),
('Ardnahoe 2022 Release', 'Ardnahoe', 'single_malt', '아일라', '스코틀랜드', 55, NULL, '버번'),
('Ardnahoe Cask Strength', 'Ardnahoe', 'single_malt', '아일라', '스코틀랜드', 58, NULL, '버번'),
('Talisker 10 Year Old', 'Talisker', 'single_malt', '아일랜즈', '스코틀랜드', 45.8, 10, NULL),
('Talisker Storm', 'Talisker', 'single_malt', '아일랜즈', '스코틀랜드', 45, NULL, NULL),
('Talisker 18 Year Old', 'Talisker', 'single_malt', '아일랜즈', '스코틀랜드', 46, 18, NULL),
('Talisker 25 Year Old', 'Talisker', 'single_malt', '아일랜즈', '스코틀랜드', 46, 25, NULL),
('Talisker Distillers Edition', 'Talisker', 'single_malt', '아일랜즈', '스코틀랜드', 46, NULL, '셰리'),
('Talisker 57°', 'Talisker', 'single_malt', '아일랜즈', '스코틀랜드', 57, NULL, NULL),
('Highland Park 12 Year Old', 'Highland Park', 'single_malt', '아일랜즈', '스코틀랜드', 43, 12, NULL),
('Highland Park 18 Year Old', 'Highland Park', 'single_malt', '아일랜즈', '스코틀랜드', 43, 18, NULL),
('Highland Park 25 Year Old', 'Highland Park', 'single_malt', '아일랜즈', '스코틀랜드', 43, 25, NULL),
('Highland Park Valkyrie', 'Highland Park', 'single_malt', '아일랜즈', '스코틀랜드', 46, NULL, '셰리'),
('Highland Park Cask Strength', 'Highland Park', 'single_malt', '아일랜즈', '스코틀랜드', 58, NULL, NULL),
('Scapa 12 Year Old', 'Scapa', 'single_malt', '아일랜즈', '스코틀랜드', 43, 12, NULL),
('Scapa 18 Year Old', 'Scapa', 'single_malt', '아일랜즈', '스코틀랜드', 43, 18, NULL),
('Scapa 21 Year Old', 'Scapa', 'single_malt', '아일랜즈', '스코틀랜드', 43, 21, NULL),
('Scapa Skiren', 'Scapa', 'single_malt', '아일랜즈', '스코틀랜드', 46, NULL, '버번'),
('Scapa 30 Year Old', 'Scapa', 'single_malt', '아일랜즈', '스코틀랜드', 43, 30, NULL),
('Jura 12 Year Old', 'Jura', 'single_malt', '아일랜즈', '스코틀랜드', 46, 12, '버번'),
('Jura 18 Year Old', 'Jura', 'single_malt', '아일랜즈', '스코틀랜드', 46, 18, '버번'),
('Jura 15 Year Old', 'Jura', 'single_malt', '아일랜즈', '스코틀랜드', 46, 15, '버번'),
('Jura Prophecy', 'Jura', 'single_malt', '아일랜즈', '스코틀랜드', 46, NULL, '버번'),
('Jura Superstition', 'Jura', 'single_malt', '아일랜즈', '스코틀랜드', 46, NULL, '버번'),
('Arran 10 Year Old', 'Arran', 'single_malt', '아일랜즈', '스코틀랜드', 46, 10, '버번'),
('Arran 14 Year Old', 'Arran', 'single_malt', '아일랜즈', '스코틀랜드', 46, 14, '버번'),
('Arran 18 Year Old', 'Arran', 'single_malt', '아일랜즈', '스코틀랜드', 46, 18, '버번'),
('Arran Family Reserve', 'Arran', 'single_malt', '아일랜즈', '스코틀랜드', 46, NULL, '버번'),
('Arran 21 Year Old', 'Arran', 'single_malt', '아일랜즈', '스코틀랜드', 46, 21, '버번'),
('Tobermory 12 Year Old', 'Tobermory', 'single_malt', '아일랜즈', '스코틀랜드', 46, 12, '버번'),
('Tobermory 21 Year Old', 'Tobermory', 'single_malt', '아일랜즈', '스코틀랜드', 46, 21, '버번'),
('Tobermory 30 Year Old', 'Tobermory', 'single_malt', '아일랜즈', '스코틀랜드', 46, 30, '버번'),
('Tobermory 15 Year Old', 'Tobermory', 'single_malt', '아일랜즈', '스코틀랜드', 46, 15, '버번'),
('Tobermory 18 Year Old', 'Tobermory', 'single_malt', '아일랜즈', '스코틀랜드', 46, 18, '버번'),
('Ledaig 10 Year Old', 'Ledaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 10, '버번'),
('Ledaig 12 Year Old', 'Ledaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 12, '버번'),
('Ledaig 15 Year Old', 'Ledaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 15, '버번'),
('Ledaig 18 Year Old', 'Ledaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 18, '버번'),
('Ledaig 21 Year Old', 'Ledaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 21, '버번'),
('Ledaig 30 Year Old', 'Ledaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 30, '버번'),
('Torabhaig 10 Year Old', 'Torabhaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 10, NULL),
('Torabhaig 12 Year Old', 'Torabhaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 12, NULL),
('Torabhaig 15 Year Old Sherry Cask Finish', 'Torabhaig', 'single_malt', '아일랜즈', '스코틀랜드', 46, 15, '셰리'),
('Isle of Raasay 10 Year Old', 'Isle of Raasay', 'single_malt', '아일랜즈', '스코틀랜드', 46, 10, NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Isle of Raasay 12 Year Old', 'Isle of Raasay', 'single_malt', '아일랜즈', '스코틀랜드', 46, 12, NULL),
('Isle of Raasay 15 Year Old Port Cask Finish', 'Isle of Raasay', 'single_malt', '아일랜즈', '스코틀랜드', 46, 15, '포트'),
('Lochranza 12 Year Old', 'Lochranza', 'single_malt', '아일랜즈', '스코틀랜드', 46, 12, NULL),
('Lochranza 15 Year Old', 'Lochranza', 'single_malt', '아일랜즈', '스코틀랜드', 46, 15, NULL),
('Lochranza 18 Year Old Sherry Cask', 'Lochranza', 'single_malt', '아일랜즈', '스코틀랜드', 46, 18, '셰리'),
('Springbank 10 Year Old', 'Springbank', 'single_malt', '캠벨타운', '스코틀랜드', 46, 10, NULL),
('Springbank 12 Year Old', 'Springbank', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, NULL),
('Springbank 15 Year Old', 'Springbank', 'single_malt', '캠벨타운', '스코틀랜드', 46, 15, NULL),
('Springbank 18 Year Old', 'Springbank', 'single_malt', '캠벨타운', '스코틀랜드', 46, 18, NULL),
('Springbank 10 Year Old Cask Strength', 'Springbank', 'single_malt', '캠벨타운', '스코틀랜드', 50, 10, '버번'),
('Springbank 12 Year Old Port Wood Finish', 'Springbank', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, '포트'),
('Springbank 12 Year Old Peated', 'Springbank', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, '버번'),
('Longrow 10 Year Old', 'Longrow', 'single_malt', '캠벨타운', '스코틀랜드', 46, 10, NULL),
('Longrow 12 Year Old', 'Longrow', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, NULL),
('Longrow 15 Year Old', 'Longrow', 'single_malt', '캠벨타운', '스코틀랜드', 46, 15, NULL),
('Longrow 12 Year Old Cask Strength', 'Longrow', 'single_malt', '캠벨타운', '스코틀랜드', 50, 12, '버번'),
('Longrow 12 Year Old Port Cask', 'Longrow', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, '포트'),
('Hazelburn 10 Year Old', 'Hazelburn', 'single_malt', '캠벨타운', '스코틀랜드', 46, 10, NULL),
('Hazelburn 12 Year Old', 'Hazelburn', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, NULL),
('Hazelburn 15 Year Old', 'Hazelburn', 'single_malt', '캠벨타운', '스코틀랜드', 46, 15, NULL),
('Hazelburn 12 Year Old Cask Strength', 'Hazelburn', 'single_malt', '캠벨타운', '스코틀랜드', 50, 12, '버번'),
('Hazelburn 12 Year Old Sherry Cask', 'Hazelburn', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, '셰리'),
('Glen Scotia 10 Year Old', 'Glen Scotia', 'single_malt', '캠벨타운', '스코틀랜드', 46, 10, NULL),
('Glen Scotia 12 Year Old', 'Glen Scotia', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, NULL),
('Glen Scotia 15 Year Old', 'Glen Scotia', 'single_malt', '캠벨타운', '스코틀랜드', 46, 15, NULL),
('Glen Scotia 12 Year Old Cask Strength', 'Glen Scotia', 'single_malt', '캠벨타운', '스코틀랜드', 50, 12, '버번'),
('Glen Scotia 12 Year Old Port Cask', 'Glen Scotia', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, '포트'),
('Kilkerran 12 Year Old', 'Kilkerran', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, NULL),
('Kilkerran 15 Year Old', 'Kilkerran', 'single_malt', '캠벨타운', '스코틀랜드', 46, 15, NULL),
('Kilkerran 18 Year Old', 'Kilkerran', 'single_malt', '캠벨타운', '스코틀랜드', 46, 18, NULL),
('Kilkerran 12 Year Old Cask Strength', 'Kilkerran', 'single_malt', '캠벨타운', '스코틀랜드', 50, 12, '버번'),
('Kilkerran 12 Year Old Sherry Cask', 'Kilkerran', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, '셰리'),
('Kilkerran 12 Year Old Port Cask', 'Kilkerran', 'single_malt', '캠벨타운', '스코틀랜드', 46, 12, '포트'),
('Auchentoshan American Oak', 'Auchentoshan', 'single_malt', '로우랜드', '스코틀랜드', 40, NULL, '버번'),
('Auchentoship 12 Year Old', 'Auchentoshan', 'single_malt', '로우랜드', '스코틀랜드', 43, 12, '버번'),
('Auchentoshan Three Wood', 'Auchentoshan', 'single_malt', '로우랜드', '스코틀랜드', 46, NULL, '버번·셰리·포트'),
('Auchentoshan 21 Year Old', 'Auchentoshan', 'single_malt', '로우랜드', '스코틀랜드', 46, 21, '버번·셰리·포트'),
('Auchentoshan 30 Year Old', 'Auchentoshan', 'single_malt', '로우랜드', '스코틀랜드', 46, 30, '버번·셰리·포트'),
('Glenkinchie 12 Year Old', 'Glenkinchie', 'single_malt', '로우랜드', '스코틀랜드', 43, 12, '버번'),
('Glenkinchie 18 Year Old', 'Glenkinchie', 'single_malt', '로우랜드', '스코틀랜드', 43, 18, '버번'),
('Glenkinchie 21 Year Old', 'Glenkinchie', 'single_malt', '로우랜드', '스코틀랜드', 43, 21, '버번'),
('Glenkinchie Distillery Exclusive 2022', 'Glenkinchie', 'single_malt', '로우랜드', '스코틀랜드', 46, NULL, '버번·셰리'),
('Bladnoch 12 Year Old', 'Bladnoch', 'single_malt', '로우랜드', '스코틀랜드', 43, 12, '버번'),
('Bladnoch 18 Year Old', 'Bladnoch', 'single_malt', '로우랜드', '스코틀랜드', 43, 18, '버번'),
('Bladnoch 21 Year Old', 'Bladnoch', 'single_malt', '로우랜드', '스코틀랜드', 43, 21, '버번'),
('Bladnoch 30 Year Old', 'Bladnoch', 'single_malt', '로우랜드', '스코틀랜드', 46, 30, '버번·셰리'),
('Bladnoch Limited Edition 2021 Port Cask', 'Bladnoch', 'single_malt', '로우랜드', '스코틀랜드', 46, NULL, '포트'),
('Kingsbarns 10 Year Old', 'Kingsbarns', 'single_malt', '로우랜드', '스코틀랜드', 46, 10, '버번'),
('Kingsbarns 12 Year Old', 'Kingsbarns', 'single_malt', '로우랜드', '스코틀랜드', 46, 12, '버번'),
('Kingsbarns 18 Year Old', 'Kingsbarns', 'single_malt', '로우랜드', '스코틀랜드', 46, 18, '버번'),
('Kingsbarns 2022 Limited Release', 'Kingsbarns', 'single_malt', '로우랜드', '스코틀랜드', 48, NULL, '버번·셰리'),
('Rosebank 10 Year Old', 'Rosebank', 'single_malt', '로우랜드', '스코틀랜드', 46, 10, '버번'),
('Rosebank 12 Year Old', 'Rosebank', 'single_malt', '로우랜드', '스코틀랜드', 46, 12, '버번'),
('Rosebank 18 Year Old', 'Rosebank', 'single_malt', '로우랜드', '스코틀랜드', 46, 18, '버번'),
('Rosebank 2021 Limited Edition', 'Rosebank', 'single_malt', '로우랜드', '스코틀랜드', 48, NULL, '버번·셰리'),
('Johnnie Walker Red Label', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('Johnnie Walker Black Label', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, NULL, '버번, 셰리'),
('Johnnie Walker Double Black', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, NULL, '버번, 셰리'),
('Johnnie Walker Green Label', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, 15, '버번, 셰리, 포트'),
('Johnnie Walker Gold Label Reserve', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, NULL, '셰리'),
('Johnnie Walker Platinum Label', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, 18, '버번, 셰리'),
('Johnnie Walker Blue Label', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, NULL, '버번, 셰리'),
('Johnnie Walker 18 Year Old', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, 18, '버번, 셰리'),
('Johnnie Walker 21 Year Old', 'Johnnie Walker', 'blended', NULL, '스코틀랜드', 40, 21, '버번, 셰리'),
('Chivas Regal 12 Year', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 12, '버번, 셰리'),
('Chivas Regal 18 Year', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 18, '버번, 셰리'),
('Chivas Regal 25 Year', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 25, '버번, 셰리'),
('Chivas Regal 12 Year Triple Wood', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 12, '버번, 셰리, 포트'),
('Chivas Regal 18 Year Mizunara', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 18, '미즈나라'),
('Chivas Regal XV', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, NULL, '버번, 셰리'),
('Chivas Regal 12 Year Gold', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 12, '버번, 셰리'),
('Chivas Regal 21 Year', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 21, '버번, 셰리'),
('Chivas Regal 30 Year', 'Chivas Regal', 'blended', NULL, '스코틀랜드', 40, 30, '버번, 셰리'),
('Ballantine''s Finest', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('Ballantine''s 12 Year', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 12, '버번, 셰리'),
('Ballantine''s 17 Year', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 17, '버번, 셰리'),
('Ballantine''s 21 Year', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 21, '버번, 셰리'),
('Ballantine''s 30 Year', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 30, '버번, 셰리'),
('Ballantine''s 12 Year Triple Wood', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 12, '버번, 셰리, 포트'),
('Ballantine''s 12 Year Special Reserve', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('Ballantine''s 21 Year Limited Edition', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 21, '버번, 셰리'),
('Ballantine''s 30 Year Limited Edition', 'Ballantine''s', 'blended', NULL, '스코틀랜드', 40, 30, '버번, 셰리'),
('Dewar''s White Label', 'Dewar''s', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('Dewar''s 12 Year', 'Dewar''s', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('Dewar''s 15 Year', 'Dewar''s', 'blended', NULL, '스코틀랜드', 40, 15, '버번'),
('Dewar''s 18 Year', 'Dewar''s', 'blended', NULL, '스코틀랜드', 40, 18, '버번'),
('Dewar''s 21 Year', 'Dewar''s', 'blended', NULL, '스코틀랜드', 40, 21, '버번'),
('Dewar''s Caribbean Smooth', 'Dewar''s', 'blended', NULL, '스코틀랜드', 40, NULL, '버번'),
('Dewar''s Signature', 'Dewar''s', 'blended', NULL, '스코틀랜드', 40, NULL, '버번'),
('The Famous Grouse', 'The Famous Grouse', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('The Famous Grouse 18 Year', 'The Famous Grouse', 'blended', NULL, '스코틀랜드', 40, 18, '버번'),
('The Famous Grouse 21 Year', 'The Famous Grouse', 'blended', NULL, '스코틀랜드', 40, 21, '버번'),
('The Famous Grouse Smoky', 'The Famous Grouse', 'blended', NULL, '스코틀랜드', 40, NULL, '버번'),
('The Famous Grouse 30 Year', 'The Famous Grouse', 'blended', NULL, '스코틀랜드', 40, 30, '버번'),
('Grant''s Family Reserve', 'Grant''s', 'blended', NULL, '스코틀랜드', 40, NULL, '버번'),
('Grant''s Triple Wood', 'Grant''s', 'blended', NULL, '스코틀랜드', 40, NULL, '버번/셰리'),
('Grant''s 10 Year', 'Grant''s', 'blended', NULL, '스코틀랜드', 40, 10, '버번'),
('Grant''s 12 Year', 'Grant''s', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('Grant''s 18 Year', 'Grant''s', 'blended', NULL, '스코틀랜드', 40, 18, '버번'),
('Grant''s 21 Year', 'Grant''s', 'blended', NULL, '스코틀랜드', 40, 21, '버번')
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Grant''s 30 Year', 'Grant''s', 'blended', NULL, '스코틀랜드', 40, 30, '버번'),
('Cutty Sark Original', 'Cutty Sark', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('Cutty Sark 12 Year', 'Cutty Sark', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('Cutty Sark 18 Year', 'Cutty Sark', 'blended', NULL, '스코틀랜드', 40, 18, '버번'),
('Cutty Sark 21 Year', 'Cutty Sark', 'blended', NULL, '스코틀랜드', 40, 21, '버번'),
('Cutty Sark 30 Year', 'Cutty Sark', 'blended', NULL, '스코틀랜드', 40, 30, '버번'),
('Royal Salute 21 Year', 'Royal Salute', 'blended', NULL, '스코틀랜드', 40, 21, '버번'),
('Royal Salute 38 Year', 'Royal Salute', 'blended', NULL, '스코틀랜드', 40, 38, '셰리'),
('Royal Salute 40 Year', 'Royal Salute', 'blended', NULL, '스코틀랜드', 40, 40, '버번'),
('Royal Salute 62 Year', 'Royal Salute', 'blended', NULL, '스코틀랜드', 40, 62, '셰리'),
('Royal Salute 100th Anniversary', 'Royal Salute', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('Old Parr 12 Year', 'Old Parr', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('Old Parr 21 Year', 'Old Parr', 'blended', NULL, '스코틀랜드', 40, 21, '셰리'),
('Old Parr 30 Year', 'Old Parr', 'blended', NULL, '스코틀랜드', 40, 30, '버번'),
('Old Parr Tribute', 'Old Parr', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('Old Parr 12 Year (Bourbon Cask)', 'Old Parr', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('J&B Rare', 'J&B', 'blended', NULL, '스코틀랜드', 40, NULL, NULL),
('J&B 18 Year', 'J&B', 'blended', NULL, '스코틀랜드', 40, 18, '버번'),
('J&B 21 Year', 'J&B', 'blended', NULL, '스코틀랜드', 40, 21, '셰리'),
('J&B 12 Year', 'J&B', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('J&B 12 Year (Sherry Cask)', 'J&B', 'blended', NULL, '스코틀랜드', 40, 12, '셰리'),
('Whyte & Mackay 12 Year', 'Whyte & Mackay', 'blended', NULL, '스코틀랜드', 40, 12, '버번'),
('Whyte & Mackay 18 Year', 'Whyte & Mackay', 'blended', NULL, '스코틀랜드', 40, 18, '버번'),
('Whyte & Mackay 21 Year', 'Whyte & Mackay', 'blended', NULL, '스코틀랜드', 40, 21, '셰리'),
('Whyte & Mackay 30 Year', 'Whyte & Mackay', 'blended', NULL, '스코틀랜드', 40, 30, '버번'),
('Whyte & Mackay 12 Year (Sherry Cask)', 'Whyte & Mackay', 'blended', NULL, '스코틀랜드', 40, 12, '셰리'),
('Monkey Shoulder Original', 'Monkey Shoulder', 'blended_malt', NULL, '스코틀랜드', 40, NULL, NULL),
('Monkey Shoulder 30 Year Old', 'Monkey Shoulder', 'blended_malt', NULL, '스코틀랜드', 43, 30, '버번, 셰리'),
('Monkey Shoulder 10 Year Old', 'Monkey Shoulder', 'blended_malt', NULL, '스코틀랜드', 43, 10, '버번, 셰리'),
('Copper Dog 12 Year Old', 'Copper Dog', 'blended_malt', NULL, '스코틀랜드', 46, 12, '버번'),
('Copper Dog 18 Year Old', 'Copper Dog', 'blended_malt', NULL, '스코틀랜드', 46, 18, '버번'),
('Copper Dog 21 Year Old', 'Copper Dog', 'blended_malt', NULL, '스코틀랜드', 46, 21, '버번'),
('Johnnie Walker Green Label 15 Year Old', 'Johnnie Walker', 'blended_malt', NULL, '스코틀랜드', 43, 15, '버번, 셰리, 포트'),
('Johnnie Walker Green Label 21 Year Old', 'Johnnie Walker', 'blended_malt', NULL, '스코틀랜드', 43, 21, '버번, 셰리, 포트'),
('Big Peat 12 Year Old', 'Big Peat', 'blended_malt', NULL, '스코틀랜드', 46, 12, '버번'),
('Big Peat 15 Year Old', 'Big Peat', 'blended_malt', NULL, '스코틀랜드', 46, 15, '버번'),
('Big Peat 18 Year Old', 'Big Peat', 'blended_malt', NULL, '스코틀랜드', 46, 18, '버번'),
('Scallywag 12 Year Old', 'Scallywag', 'blended_malt', NULL, '스코틀랜드', 46, 12, '버번'),
('Scallywag 15 Year Old', 'Scallywag', 'blended_malt', NULL, '스코틀랜드', 46, 15, '버번'),
('Scallywag 18 Year Old', 'Scallywag', 'blended_malt', NULL, '스코틀랜드', 46, 18, '버번'),
('Timorous Beastie 12 Year Old', 'Timorous Beastie', 'blended_malt', NULL, '스코틀랜드', 46, 12, '버번'),
('Timorous Beastie 15 Year Old', 'Timorous Beastie', 'blended_malt', NULL, '스코틀랜드', 46, 15, '버번'),
('Timorous Beastie 18 Year Old', 'Timorous Beastie', 'blended_malt', NULL, '스코틀랜드', 46, 18, '버번'),
('Haig Club', 'Haig Club', 'grain', NULL, '스코틀랜드', 40, NULL, NULL),
('Haig Club 12 Year', 'Haig Club', 'grain', NULL, '스코틀랜드', 46, 12, '버번'),
('Haig Club 18 Year', 'Haig Club', 'grain', NULL, '스코틀랜드', 46, 18, '버번'),
('Haig Club Sherry Cask', 'Haig Club', 'grain', NULL, '스코틀랜드', 46, 12, '셰리'),
('Haig Club Limited Edition Cask Strength', 'Haig Club', 'grain', NULL, '스코틀랜드', 55, NULL, NULL),
('Girvan Single Malt', 'Girvan', 'grain', NULL, '스코틀랜드', 46, NULL, NULL),
('Girvan 12 Year', 'Girvan', 'grain', NULL, '스코틀랜드', 46, 12, '버번'),
('Girvan 15 Year', 'Girvan', 'grain', NULL, '스코틀랜드', 46, 15, '버번'),
('Girvan 18 Year', 'Girvan', 'grain', NULL, '스코틀랜드', 46, 18, '버번'),
('Girvan 30 Year', 'Girvan', 'grain', NULL, '스코틀랜드', 46, 30, '버번'),
('Cameronbridge Single Grain', 'Cameronbridge', 'grain', NULL, '스코틀랜드', 40, NULL, NULL),
('Cameronbridge 12 Year', 'Cameronbridge', 'grain', NULL, '스코틀랜드', 46, 12, '버번'),
('Cameronbridge 15 Year', 'Cameronbridge', 'grain', NULL, '스코틀랜드', 46, 15, '버번'),
('Cameronbridge 18 Year', 'Cameronbridge', 'grain', NULL, '스코틀랜드', 46, 18, '버번'),
('Cameronbridge 30 Year', 'Cameronbridge', 'grain', NULL, '스코틀랜드', 46, 30, '버번'),
('North British 12 Year', 'North British', 'grain', NULL, '스코틀랜드', 46, 12, '버번'),
('North British 15 Year', 'North British', 'grain', NULL, '스코틀랜드', 46, 15, '버번'),
('North British 18 Year', 'North British', 'grain', NULL, '스코틀랜드', 46, 18, '버번'),
('North British 21 Year', 'North British', 'grain', NULL, '스코틀랜드', 46, 21, '버번'),
('North British 30 Year', 'North British', 'grain', NULL, '스코틀랜드', 46, 30, '버번'),
('Buffalo Trace Bourbon', 'Buffalo Trace', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Buffalo Trace 12 Year Bourbon', 'Buffalo Trace', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('Buffalo Trace 17 Year Bourbon', 'Buffalo Trace', 'bourbon', '켄터키', '미국', 45, 17, '버번'),
('Buffalo Trace 20 Year Bourbon', 'Buffalo Trace', 'bourbon', '켄터키', '미국', 45, 20, '버번'),
('Buffalo Trace Rye', 'Buffalo Trace', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Eagle Rare 10 Year Bourbon', 'Eagle Rare', 'bourbon', '켄터키', '미국', 45, 10, '버번'),
('Eagle Rare 12 Year Bourbon', 'Eagle Rare', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('Eagle Rare 17 Year Bourbon', 'Eagle Rare', 'bourbon', '켄터키', '미국', 45, 17, '버번'),
('Eagle Rare 6 Year Bourbon', 'Eagle Rare', 'bourbon', '켄터키', '미국', 45, 6, '버번'),
('Blanton''s Single Barrel Bourbon', 'Blanton''s', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Blanton''s Gold Edition', 'Blanton''s', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Blanton''s 12 Year Bourbon', 'Blanton''s', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('W.L. Weller Special Reserve Bourbon', 'W.L. Weller', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('W.L. Weller Antique 107 Bourbon', 'W.L. Weller', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('W.L. Weller 12 Year Bourbon', 'W.L. Weller', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('W.L. Weller 15 Year Bourbon', 'W.L. Weller', 'bourbon', '켄터키', '미국', 45, 15, '버번'),
('E.H. Taylor Jr. Straight Rye Whiskey', 'E.H. Taylor', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('E.H. Taylor Small Batch Bourbon', 'E.H. Taylor', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('E.H. Taylor Single Barrel Bourbon', 'E.H. Taylor', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('E.H. Taylor 12 Year Bourbon', 'E.H. Taylor', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('E.H. Taylor 15 Year Bourbon', 'E.H. Taylor', 'bourbon', '켄터키', '미국', 45, 15, '버번'),
('Maker''s Mark', 'Maker''s Mark', 'bourbon', '켄터키', '미국', 45, NULL, '아메리칸 오크'),
('Maker''s Mark 46', 'Maker''s Mark', 'bourbon', '켄터키', '미국', 46, NULL, '아메리칸 오크'),
('Maker''s Mark 101', 'Maker''s Mark', 'bourbon', '켄터키', '미국', 50.5, NULL, '아메리칸 오크'),
('Maker''s Mark Private Select', 'Maker''s Mark', 'bourbon', '켄터키', '미국', 45, NULL, NULL),
('Wild Turkey 101', 'Wild Turkey', 'bourbon', '켄터키', '미국', 50.5, NULL, '아메리칸 오크'),
('Wild Turkey Rare Breed', 'Wild Turkey', 'bourbon', '켄터키', '미국', 56.4, NULL, '아메리칸 오크'),
('Wild Turkey 81', 'Wild Turkey', 'bourbon', '켄터키', '미국', 40.5, NULL, '아메리칸 오크'),
('Wild Turkey Master''s Keep', 'Wild Turkey', 'bourbon', '켄터키', '미국', 50, NULL, NULL),
('Russell''s Reserve 10 Year', 'Russell''s Reserve', 'bourbon', '켄터키', '미국', 46, 10, '아메리칸 오크'),
('Russell''s Reserve Single Barrel', 'Russell''s Reserve', 'bourbon', '켄터키', '미국', 46, NULL, '아메리칸 오크'),
('Russell''s Reserve 22 Year', 'Russell''s Reserve', 'bourbon', '켄터키', '미국', 46, 22, '아메리칸 오크'),
('Russell''s Reserve 30 Year', 'Russell''s Reserve', 'bourbon', '켄터키', '미국', 46, 30, '아메리칸 오크'),
('Four Roses Single Barrel', 'Four Roses', 'bourbon', '켄터키', '미국', 45, NULL, '아메리칸 오크'),
('Four Roses Small Batch', 'Four Roses', 'bourbon', '켄터키', '미국', 45, NULL, '아메리칸 오크'),
('Four Roses 18 Year', 'Four Roses', 'bourbon', '켄터키', '미국', 45, 18, '아메리칸 오크'),
('Four Roses Limited Edition', 'Four Roses', 'bourbon', '켄터키', '미국', 45, NULL, NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Jim Beam White Label', 'Jim Beam', 'bourbon', '켄터키', '미국', 40, NULL, '버번'),
('Jim Beam Black', 'Jim Beam', 'bourbon', '켄터키', '미국', 43, NULL, '버번'),
('Jim Beam Devil''s Cut', 'Jim Beam', 'bourbon', '켄터키', '미국', 43, NULL, '버번'),
('Jim Beam Double Oak', 'Jim Beam', 'bourbon', '켄터키', '미국', 40, NULL, '버번'),
('Jim Beam Rye', 'Jim Beam', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Jim Beam 12 Year Old', 'Jim Beam', 'bourbon', '켄터키', '미국', 40, 12, '버번'),
('Knob Creek 9 Year Old', 'Knob Creek', 'bourbon', '켄터키', '미국', 50, 9, '버번'),
('Knob Creek Single Barrel', 'Knob Creek', 'bourbon', '켄터키', '미국', 53, NULL, '버번'),
('Knob Creek 12 Year Old', 'Knob Creek', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('Knob Creek Rye', 'Knob Creek', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Knob Creek 15 Year Old', 'Knob Creek', 'bourbon', '켄터키', '미국', 45, 15, '버번'),
('Booker''s Bourbon', 'Booker’s', 'bourbon', '켄터키', '미국', 62.5, NULL, '버번'),
('Booker''s Rye', 'Booker’s', 'bourbon', '켄터키', '미국', 62.5, NULL, '버번'),
('Booker''s 12 Year Old', 'Booker’s', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('Basil Hayden''s', 'Basil Hayden’s', 'bourbon', '켄터키', '미국', 40, NULL, '버번'),
('Basil Hayden''s 10 Year Old', 'Basil Hayden’s', 'bourbon', '켄터키', '미국', 40, 10, '버번'),
('Basil Hayden''s Rye', 'Basil Hayden’s', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Old Grand-Dad Bonded', 'Old Grand-Dad', 'bourbon', '켄터키', '미국', 40, NULL, '버번'),
('Old Grand-Dad 114', 'Old Grand-Dad', 'bourbon', '켄터키', '미국', 46.5, NULL, '버번'),
('Old Grand-Dad 8 Year Old', 'Old Grand-Dad', 'bourbon', '켄터키', '미국', 40, 8, '버번'),
('Old Grand-Dad 12 Year Old', 'Old Grand-Dad', 'bourbon', '켄터키', '미국', 45, 12, '버번'),
('Old Grand-Dad Rye', 'Old Grand-Dad', 'bourbon', '켄터키', '미국', 45, NULL, '버번'),
('Woodford Reserve Kentucky Straight Bourbon Whiskey', 'Woodford Reserve', 'bourbon', '켄터키', '미국', 45.2, NULL, NULL),
('Woodford Reserve Double Oaked', 'Woodford Reserve', 'bourbon', '켄터키', '미국', 45.2, NULL, '버번'),
('Woodford Reserve Master''s Collection 2010', 'Woodford Reserve', 'bourbon', '켄터키', '미국', 45.2, NULL, '버번'),
('Woodford Reserve Master''s Collection 2014', 'Woodford Reserve', 'bourbon', '켄터키', '미국', 45.2, NULL, '버번'),
('Woodford Reserve Rye Whiskey', 'Woodford Reserve', 'bourbon', '켄터키', '미국', 45.2, NULL, NULL),
('Old Forester 86 Proof Kentucky Straight Bourbon', 'Old Forester', 'bourbon', '켄터키', '미국', 43, NULL, NULL),
('Old Forester 100 Proof Kentucky Straight Bourbon', 'Old Forester', 'bourbon', '켄터키', '미국', 50, NULL, NULL),
('Old Forester Birthday Bourbon', 'Old Forester', 'bourbon', '켄터키', '미국', 45, NULL, NULL),
('Old Forester 1897 Kentucky Straight Bourbon Whiskey', 'Old Forester', 'bourbon', '켄터키', '미국', 45, 10, NULL),
('Old Forester 12 Year Kentucky Straight Bourbon', 'Old Forester', 'bourbon', '켄터키', '미국', 45, 12, NULL),
('Elijah Craig Small Batch Bourbon', 'Elijah Craig', 'bourbon', '켄터키', '미국', 47, NULL, NULL),
('Elijah Craig Barrel Proof', 'Elijah Craig', 'bourbon', '켄터키', '미국', 62, NULL, NULL),
('Elijah Craig 12 Year Small Batch', 'Elijah Craig', 'bourbon', '켄터키', '미국', 45, 12, NULL),
('Elijah Craig Toasted Oak', 'Elijah Craig', 'bourbon', '켄터키', '미국', 45, NULL, NULL),
('Elijah Craig 18 Year Small Batch', 'Elijah Craig', 'bourbon', '켄터키', '미국', 45, 18, NULL),
('Evan Williams Black Label Kentucky Straight Bourbon', 'Evan Williams', 'bourbon', '켄터키', '미국', 43, NULL, NULL),
('Evan Williams 12 Year Kentucky Straight Bourbon', 'Evan Williams', 'bourbon', '켄터키', '미국', 45, 12, NULL),
('Evan Williams Single Barrel', 'Evan Williams', 'bourbon', '켄터키', '미국', 45, NULL, NULL),
('Evan Williams Bottled-in-Bond', 'Evan Williams', 'bourbon', '켄터키', '미국', 50, NULL, NULL),
('Evan Williams 18 Year Kentucky Straight Bourbon', 'Evan Williams', 'bourbon', '켄터키', '미국', 45, 18, NULL),
('Michter''s Original US*1 Rye Whiskey', 'Michter''s', 'bourbon', NULL, '미국', 45, NULL, NULL),
('Michter''s US*1 Single Barrel Rye', 'Michter''s', 'bourbon', NULL, '미국', 45, NULL, NULL),
('Michter''s 10 Year Old Straight Rye', 'Michter''s', 'bourbon', NULL, '미국', 45, 10, NULL),
('Michter''s 20 Year Old Straight Rye', 'Michter''s', 'bourbon', NULL, '미국', 45, 20, NULL),
('Michter''s 25 Year Old Straight Rye', 'Michter''s', 'bourbon', NULL, '미국', 45, 25, NULL),
('1792 Full Proof Bourbon', '1792', 'bourbon', NULL, '미국', 50.5, NULL, NULL),
('1792 Small Batch Bourbon', '1792', 'bourbon', NULL, '미국', 45, NULL, NULL),
('1792 Single Barrel Bourbon', '1792', 'bourbon', NULL, '미국', 45, NULL, NULL),
('1792 12 Year Old Bourbon', '1792', 'bourbon', NULL, '미국', 45, 12, NULL),
('1792 18 Year Old Bourbon', '1792', 'bourbon', NULL, '미국', 45, 18, NULL),
('Heaven Hill Bottled-in-Bond Kentucky Straight Bourbon', 'Heaven Hill', 'bourbon', NULL, '미국', 50, NULL, NULL),
('Heaven Hill 8 Year Old Kentucky Straight Bourbon', 'Heaven Hill', 'bourbon', NULL, '미국', 45, 8, NULL),
('Heaven Hill 12 Year Old Kentucky Straight Bourbon', 'Heaven Hill', 'bourbon', NULL, '미국', 45, 12, NULL),
('Heaven Hill 18 Year Old Kentucky Straight Bourbon', 'Heaven Hill', 'bourbon', NULL, '미국', 45, 18, NULL),
('Heaven Hill 20 Year Old Kentucky Straight Bourbon', 'Heaven Hill', 'bourbon', NULL, '미국', 45, 20, NULL),
('Very Old Barton 8 Year Old Kentucky Straight Bourbon', 'Very Old Barton', 'bourbon', NULL, '미국', 45, 8, NULL),
('Very Old Barton 12 Year Old Kentucky Straight Bourbon', 'Very Old Barton', 'bourbon', NULL, '미국', 45, 12, NULL),
('Very Old Barton 15 Year Old Kentucky Straight Bourbon', 'Very Old Barton', 'bourbon', NULL, '미국', 45, 15, NULL),
('Very Old Barton 20 Year Old Kentucky Straight Bourbon', 'Very Old Barton', 'bourbon', NULL, '미국', 45, 20, NULL),
('Larceny Small Batch Bourbon', 'Larceny', 'bourbon', NULL, '미국', 45, NULL, NULL),
('Larceny 8 Year Old Bourbon', 'Larceny', 'bourbon', NULL, '미국', 45, 8, NULL),
('Larceny 12 Year Old Bourbon', 'Larceny', 'bourbon', NULL, '미국', 45, 12, NULL),
('Larceny 18 Year Old Bourbon', 'Larceny', 'bourbon', NULL, '미국', 45, 18, NULL),
('Larceny 20 Year Old Bourbon', 'Larceny', 'bourbon', NULL, '미국', 45, 20, NULL),
('Rittenhouse Rye 100 Proof', 'Rittenhouse', 'rye', NULL, '미국', 50, NULL, '버번'),
('Rittenhouse Rye 110 Proof', 'Rittenhouse', 'rye', NULL, '미국', 55, NULL, '버번'),
('Rittenhouse Rye Cask Strength', 'Rittenhouse', 'rye', NULL, '미국', NULL, NULL, '버번'),
('Sazerac 12 Year Rye', 'Sazerac Rye', 'rye', NULL, '미국', 45, 12, '버번'),
('Sazerac 18 Year Rye', 'Sazerac Rye', 'rye', NULL, '미국', 45, 18, '버번'),
('Sazerac Rye (NAS)', 'Sazerac Rye', 'rye', NULL, '미국', NULL, NULL, '버번'),
('WhistlePig Rye', 'WhistlePig', 'rye', NULL, '미국', 45, NULL, '버번'),
('WhistlePig 10 Year Straight Rye', 'WhistlePig', 'rye', NULL, '미국', 45, 10, '버번'),
('WhistlePig 12 Year Straight Rye', 'WhistlePig', 'rye', NULL, '미국', 45, 12, '버번'),
('WhistlePig 15 Year Straight Rye', 'WhistlePig', 'rye', NULL, '미국', 45, 15, '버번'),
('WhistlePig The Boss Hog', 'WhistlePig', 'rye', NULL, '미국', 50, NULL, '버번'),
('Michter''s Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, NULL, '버번'),
('Michter''s 10 Year Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, 10, '버번'),
('Michter''s 12 Year Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, 12, '버번'),
('Michter''s 15 Year Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, 15, '버번'),
('Michter''s 18 Year Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, 18, '버번'),
('Michter''s 20 Year Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, 20, '버번'),
('Michter''s 25 Year Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, 25, '버번'),
('Michter''s 30 Year Rye', 'Michter''s Rye', 'rye', NULL, '미국', 45, 30, '버번'),
('Bulleit Rye Whiskey', 'Bulleit Rye', 'rye', NULL, '미국', 45, NULL, '버번'),
('Bulleit Rye 10 Year', 'Bulleit Rye', 'rye', NULL, '미국', 45, 10, '버번'),
('Bulleit Rye Barrel Proof', 'Bulleit Rye', 'rye', NULL, '미국', 50, NULL, '버번'),
('Knob Creek Rye Whiskey', 'Knob Creek Rye', 'rye', NULL, '미국', 50, NULL, '버번'),
('Knob Creek Rye 12 Year', 'Knob Creek Rye', 'rye', NULL, '미국', 45, 12, '버번'),
('Knob Creek Rye Single Barrel', 'Knob Creek Rye', 'rye', NULL, '미국', 50, NULL, '버번'),
('High West Double Rye', 'High West', 'rye', NULL, '미국', 45, NULL, '버번'),
('High West Rendezvous Rye', 'High West', 'rye', NULL, '미국', 45, 5, '버번'),
('High West Rye', 'High West', 'rye', NULL, '미국', 45, NULL, '버번'),
('Old Overholt Rye Whiskey', 'Old Overholt', 'rye', NULL, '미국', 40, NULL, '버번'),
('Old Overholt 8 Year Rye', 'Old Overholt', 'rye', NULL, '미국', 45, 8, '버번'),
('Old Overholt Rye 100 Proof', 'Old Overholt', 'rye', NULL, '미국', 50, NULL, '버번'),
('Jack Daniel''s Old No. 7', 'Jack Daniel''s', 'other', '테네시', '미국', 40, NULL, NULL),
('Jack Daniel''s Gentleman Jack', 'Jack Daniel''s', 'other', '테네시', '미국', 40, NULL, NULL),
('Jack Daniel''s Single Barrel Select', 'Jack Daniel''s', 'other', '테네시', '미국', 43.5, NULL, NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Jack Daniel''s Tennessee Honey', 'Jack Daniel''s', 'other', '테네시', '미국', 35, NULL, NULL),
('Jack Daniel''s Tennessee Fire', 'Jack Daniel''s', 'other', '테네시', '미국', 35, NULL, NULL),
('Jack Daniel''s Single Barrel Rye', 'Jack Daniel''s', 'other', '테네시', '미국', 45, NULL, NULL),
('Jack Daniel''s 12 Year Old Tennessee Whiskey', 'Jack Daniel''s', 'other', '테네시', '미국', 43.5, 12, NULL),
('Jack Daniel''s 18 Year Old Tennessee Whiskey', 'Jack Daniel''s', 'other', '테네시', '미국', 43.5, 18, NULL),
('George Dickel No. 8', 'George Dickel', 'other', '테네시', '미국', 40, NULL, NULL),
('George Dickel No. 12', 'George Dickel', 'other', '테네시', '미국', 43.5, NULL, NULL),
('George Dickel Barrel Select', 'George Dickel', 'other', '테네시', '미국', 45, NULL, NULL),
('George Dickel Rye', 'George Dickel', 'other', '테네시', '미국', 45, NULL, NULL),
('George Dickel 12 Year Old', 'George Dickel', 'other', '테네시', '미국', 45, 12, NULL),
('George Dickel 15 Year Old', 'George Dickel', 'other', '테네시', '미국', 45, 15, NULL),
('Uncle Nearest Premium Whiskey', 'Uncle Nearest', 'other', '테네시', '미국', 43.5, NULL, NULL),
('Uncle Nearest 12 Year Old', 'Uncle Nearest', 'other', '테네시', '미국', 45, 12, NULL),
('Uncle Nearest 18 Year Old', 'Uncle Nearest', 'other', '테네시', '미국', 45, 18, NULL),
('Uncle Nearest Single Barrel', 'Uncle Nearest', 'other', '테네시', '미국', 45, NULL, NULL),
('Uncle Nearest Rye', 'Uncle Nearest', 'other', '테네시', '미국', 45, NULL, NULL),
('Jameson Original Irish Whiskey', 'Jameson', 'irish', NULL, '아일랜드', 40, NULL, NULL),
('Jameson Black Barrel Irish Whiskey', 'Jameson', 'irish', NULL, '아일랜드', 43, NULL, '버번'),
('Jameson 18 Year Old Single Malt Irish Whiskey', 'Jameson', 'irish', NULL, '아일랜드', 43, 18, '버번'),
('Jameson Caskmates Stout Edition', 'Jameson', 'irish', NULL, '아일랜드', 46, NULL, '스투트'),
('Bushmills Original Irish Whiskey', 'Bushmills', 'irish', NULL, '아일랜드', 40, NULL, NULL),
('Bushmills Black Bush Irish Whiskey', 'Bushmills', 'irish', NULL, '아일랜드', 43, NULL, '버번'),
('Bushmills 10 Year Old Single Malt', 'Bushmills', 'irish', NULL, '아일랜드', 43, 10, '버번'),
('Bushmills 21 Year Old Single Malt', 'Bushmills', 'irish', NULL, '아일랜드', 43, 21, '버번'),
('Bushmills 16 Year Old Cask Strength', 'Bushmills', 'irish', NULL, '아일랜드', 57.5, 16, '버번'),
('Tullamore D.E.W. Original Irish Whiskey', 'Tullamore D.E.W.', 'irish', NULL, '아일랜드', 40, NULL, NULL),
('Tullamore D.E.W. 12 Year Old Single Malt', 'Tullamore D.E.W.', 'irish', NULL, '아일랜드', 43, 12, '버번'),
('Tullamore D.E.W. 14 Year Old Single Malt', 'Tullamore D.E.W.', 'irish', NULL, '아일랜드', 43, 14, '버번'),
('Tullamore D.E.W. Cask Strength Irish Whiskey', 'Tullamore D.E.W.', 'irish', NULL, '아일랜드', 55, NULL, NULL),
('Tullamore D.E.W. Special Reserve', 'Tullamore D.E.W.', 'irish', NULL, '아일랜드', 43, NULL, NULL),
('Redbreast 12 Year Old', 'Redbreast', 'irish', NULL, '아일랜드', 40, 12, '포트, 쉐리'),
('Redbreast 15 Year Old', 'Redbreast', 'irish', NULL, '아일랜드', 46, 15, '포트, 쉐리'),
('Redbreast 21 Year Old', 'Redbreast', 'irish', NULL, '아일랜드', 46, 21, '포트, 쉐리'),
('Redbreast 12 Year Old Cask Strength', 'Redbreast', 'irish', NULL, '아일랜드', 57.8, 12, '포트, 쉐리'),
('Redbreast Lustau', 'Redbreast', 'irish', NULL, '아일랜드', 46, NULL, '쉐리'),
('Green Spot', 'Green Spot', 'irish', NULL, '아일랜드', 40, NULL, '버번, 포트'),
('Green Spot 12 Year Old', 'Green Spot', 'irish', NULL, '아일랜드', 46, 12, '버번, 포트'),
('Green Spot 21 Year Old', 'Green Spot', 'irish', NULL, '아일랜드', 46, 21, '버번, 포트'),
('Green Spot Château Léoville Barton', 'Green Spot', 'irish', NULL, '아일랜드', 46, NULL, '버번, 포트'),
('Green Spot 30 Year Old', 'Green Spot', 'irish', NULL, '아일랜드', 46, 30, '버번, 포트'),
('Yellow Spot 12 Year Old', 'Yellow Spot', 'irish', NULL, '아일랜드', 43, 12, '버번, 포트'),
('Yellow Spot 15 Year Old', 'Yellow Spot', 'irish', NULL, '아일랜드', 46, 15, '버번, 포트'),
('Yellow Spot 18 Year Old', 'Yellow Spot', 'irish', NULL, '아일랜드', 46, 18, '버번, 포트'),
('Yellow Spot 21 Year Old', 'Yellow Spot', 'irish', NULL, '아일랜드', 46, 21, '버번, 포트'),
('Yellow Spot 30 Year Old', 'Yellow Spot', 'irish', NULL, '아일랜드', 46, 30, '버번, 포트'),
('Powers Gold Label', 'Powers', 'irish', NULL, '아일랜드', 40, NULL, '버번'),
('Powers John’s Lane Release 12 Year Old', 'Powers', 'irish', NULL, '아일랜드', 46, 12, '버번'),
('Powers Signature', 'Powers', 'irish', NULL, '아일랜드', 46, 8, '버번'),
('Powers 15 Year Old', 'Powers', 'irish', NULL, '아일랜드', 46, 15, '버번'),
('Powers 18 Year Old', 'Powers', 'irish', NULL, '아일랜드', 46, 18, '버번'),
('Midleton Very Rare', 'Midleton', 'irish', NULL, '아일랜드', 46, NULL, '버번, 포트'),
('Midleton Very Rare 2015', 'Midleton', 'irish', NULL, '아일랜드', 46, 12, '버번, 포트'),
('Midleton Very Rare 2018', 'Midleton', 'irish', NULL, '아일랜드', 46, 12, '버번, 포트'),
('Midleton Very Rare 2020', 'Midleton', 'irish', NULL, '아일랜드', 46, 12, '버번, 포트'),
('Midleton Very Rare 2022', 'Midleton', 'irish', NULL, '아일랜드', 46, 12, '버번, 포트'),
('Teeling Small Batch', 'Teeling', 'irish', NULL, '아일랜드', 46, NULL, '버번'),
('Teeling Single Grain', 'Teeling', 'irish', NULL, '아일랜드', 46, NULL, '버번'),
('Teeling 24 Year Old', 'Teeling', 'irish', NULL, '아일랜드', 46, 24, '버번·셰리'),
('Teeling Batch 22', 'Teeling', 'irish', NULL, '아일랜드', 46, 22, '버번·포트'),
('Connemara Peated Single Malt', 'Connemara', 'irish', NULL, '아일랜드', 46, NULL, '버번'),
('Connemara 12 Year Old', 'Connemara', 'irish', NULL, '아일랜드', 46, 12, '버번·시ェ리'),
('Connemara Peated 16 Year Old', 'Connemara', 'irish', NULL, '아일랜드', 46, 16, '버번·시ェ리'),
('Waterford Single Grain', 'Waterford', 'irish', NULL, '아일랜드', 46, NULL, '버번'),
('Waterford 12 Year Old Single Malt', 'Waterford', 'irish', NULL, '아일랜드', 46, 12, '버번·시ェ리'),
('Waterford 21 Year Old Single Malt', 'Waterford', 'irish', NULL, '아일랜드', 46, 21, '버번·시ェ리·포트'),
('West Cork Irish Single Malt', 'West Cork', 'irish', NULL, '아일랜드', 46, NULL, '버번'),
('West Cork 12 Year Old', 'West Cork', 'irish', NULL, '아일랜드', 46, 12, '버번·시ェ리'),
('West Cork 21 Year Old', 'West Cork', 'irish', NULL, '아일랜드', 46, 21, '버번·시ェ리·포트'),
('Yamazaki 12 Year Old', 'Yamazaki', 'japanese', NULL, '일본', 43, 12, '버번'),
('Yamazaki 18 Year Old', 'Yamazaki', 'japanese', NULL, '일본', 43, 18, '버번'),
('Yamazaki 25 Year Old', 'Yamazaki', 'japanese', NULL, '일본', 43, 25, '버번'),
('Yamazaki Sherry Cask', 'Yamazaki', 'japanese', NULL, '일본', 43, NULL, '셰리'),
('Yamazaki Distiller''s Reserve', 'Yamazaki', 'japanese', NULL, '일본', 45, NULL, NULL),
('Hakushu 12 Year Old', 'Hakushu', 'japanese', NULL, '일본', 43, 12, '버번'),
('Hakushu 18 Year Old', 'Hakushu', 'japanese', NULL, '일본', 43, 18, '버번'),
('Hakushu Distiller''s Reserve', 'Hakushu', 'japanese', NULL, '일본', 45, NULL, NULL),
('Hakushu Forest', 'Hakushu', 'japanese', NULL, '일본', 43, NULL, '버번'),
('Hibiki Harmony', 'Hibiki', 'japanese', NULL, '일본', 43, NULL, NULL),
('Hibiki 12 Year Old', 'Hibiki', 'japanese', NULL, '일본', 43, 12, '버번'),
('Hibiki 17 Year Old', 'Hibiki', 'japanese', NULL, '일본', 43, 17, '버번'),
('Hibiki 21 Year Old', 'Hibiki', 'japanese', NULL, '일본', 43, 21, '버번'),
('Hibiki 30 Year Old', 'Hibiki', 'japanese', NULL, '일본', 43, 30, '버번'),
('Suntory Toki', 'Suntory Toki', 'japanese', NULL, '일본', 43, NULL, NULL),
('Suntory Toki Mizunara', 'Suntory Toki', 'japanese', NULL, '일본', 43, NULL, '미즈나라'),
('Suntory Toki Japanese Harmony', 'Suntory Toki', 'japanese', NULL, '일본', 43, NULL, NULL),
('The Chita', 'The Chita', 'japanese', NULL, '일본', 43, NULL, NULL),
('The Chita Mizunara', 'The Chita', 'japanese', NULL, '일본', 43, NULL, '미즈나라'),
('The Chita Grain Whisky', 'The Chita', 'japanese', NULL, '일본', 43, NULL, NULL),
('Yoichi Single Malt', 'Nikka Yoichi', 'japanese', NULL, '일본', 43, NULL, NULL),
('Yoichi 10 Year', 'Nikka Yoichi', 'japanese', NULL, '일본', 43, 10, NULL),
('Yoichi 15 Year', 'Nikka Yoichi', 'japanese', NULL, '일본', 43, 15, NULL),
('Yoichi Peated', 'Nikka Yoichi', 'japanese', NULL, '일본', 45, NULL, NULL),
('Yoichi Sherry Cask', 'Nikka Yoichi', 'japanese', NULL, '일본', 45, NULL, '셰리'),
('Miyagikyo Single Malt', 'Nikka Miyagikyo', 'japanese', NULL, '일본', 43, NULL, NULL),
('Miyagikyo 10 Year', 'Nikka Miyagikyo', 'japanese', NULL, '일본', 43, 10, NULL),
('Miyagikyo 15 Year', 'Nikka Miyagikyo', 'japanese', NULL, '일본', 43, 15, NULL),
('Miyagikyo Sherry Cask', 'Nikka Miyagikyo', 'japanese', NULL, '일본', 45, NULL, '셰리'),
('Miyagikyo Peated', 'Nikka Miyagikyo', 'japanese', NULL, '일본', 45, NULL, NULL),
('From the Barrel', 'Nikka From the Barrel', 'japanese', NULL, '일본', 51.4, NULL, NULL),
('Coffey Grain', 'Nikka Coffey Grain', 'japanese', NULL, '일본', 45, NULL, NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Taketsuru Pure Malt', 'Nikka Taketsuru', 'japanese', NULL, '일본', 43, NULL, NULL),
('Taketsuru 12 Year', 'Nikka Taketsuru', 'japanese', NULL, '일본', 43, 12, NULL),
('Taketsuru 18 Year', 'Nikka Taketsuru', 'japanese', NULL, '일본', 43, 18, NULL),
('Taketsuru 30 Year', 'Nikka Taketsuru', 'japanese', NULL, '일본', 43, 30, NULL),
('Taketsuru 50 Year', 'Nikka Taketsuru', 'japanese', NULL, '일본', 43, 50, NULL),
('Ichiro''s Malt Chichibu The First', 'Ichiro''s Malt Chichibu', 'japanese', NULL, '일본', 46, 3, '버번'),
('Ichiro''s Malt Chichibu The First Peated', 'Ichiro''s Malt Chichibu', 'japanese', NULL, '일본', 46, 3, '피트'),
('Ichiro''s Malt Chichibu The First Sherry Cask', 'Ichiro''s Malt Chichibu', 'japanese', NULL, '일본', 46, 3, '셰리'),
('Ichiro''s Malt Chichibu The First Limited Edition 2020', 'Ichiro''s Malt Chichibu', 'japanese', NULL, '일본', 46, 3, NULL),
('Mars Shinshu Komagatake 2020', 'Mars Shinshu', 'japanese', NULL, '일본', 46, 5, '버번'),
('Mars Shinshu Komagatake 2021 Sherry Cask', 'Mars Shinshu', 'japanese', NULL, '일본', 46, 5, '셰리'),
('Mars Shinshu Komagatake 2022 Peated', 'Mars Shinshu', 'japanese', NULL, '일본', 46, 5, '피트'),
('Mars Shinshu The First Edition', 'Mars Shinshu', 'japanese', NULL, '일본', 45, 3, NULL),
('Akkeshi Single Malt 2018', 'Akkeshi', 'japanese', NULL, '일본', 45, 5, '버번'),
('Akkeshi Single Malt 2020 Sherry Cask', 'Akkeshi', 'japanese', NULL, '일본', 45, 5, '셰리'),
('Akkeshi Single Malt 2021 Peated', 'Akkeshi', 'japanese', NULL, '일본', 45, 5, '피트'),
('Akkeshi Limited Edition 2022', 'Akkeshi', 'japanese', NULL, '일본', 45, NULL, NULL),
('Kanosuke Single Malt 2019', 'Kanosuke', 'japanese', NULL, '일본', 46, 4, '버번'),
('Kanosuke Single Malt 2020 Sherry Cask', 'Kanosuke', 'japanese', NULL, '일본', 46, 4, '셰리'),
('Kanosuke Single Malt 2021 Peated', 'Kanosuke', 'japanese', NULL, '일본', 46, 4, '피트'),
('Kanosuke Limited Edition 2022', 'Kanosuke', 'japanese', NULL, '일본', 46, NULL, NULL),
('Kavalan Solist Vinho Barrique', 'Kavalan', 'other', NULL, '대만', 55, NULL, '바르케'),
('Kavalan Solist Sherry Cask', 'Kavalan', 'other', NULL, '대만', 55, NULL, '셰리'),
('Kavalan Solist Port Cask', 'Kavalan', 'other', NULL, '대만', 55, NULL, '포트'),
('Kavalan Solist Rum Cask Finish', 'Kavalan', 'other', NULL, '대만', 55, NULL, '럼'),
('Kavalan Classic Single Malt', 'Kavalan', 'other', NULL, '대만', 40, NULL, NULL),
('Kavalan Single Cask 2013', 'Kavalan', 'other', NULL, '대만', 55, NULL, NULL),
('Omar 5 Year Single Malt', 'Omar', 'other', NULL, '대만', 40, 5, NULL),
('Omar 8 Year Single Malt', 'Omar', 'other', NULL, '대만', 40, 8, NULL),
('Omar 12 Year Single Malt', 'Omar', 'other', NULL, '대만', 40, 12, NULL),
('Omar 18 Year Single Malt', 'Omar', 'other', NULL, '대만', 40, 18, NULL),
('Omar 25 Year Single Malt', 'Omar', 'other', NULL, '대만', 40, 25, NULL),
('Omar Cask Strength', 'Omar', 'other', NULL, '대만', 58, NULL, NULL),
('Omar Sherry Cask Finish', 'Omar', 'other', NULL, '대만', 45, NULL, '셰리'),
('Omar Port Cask Finish', 'Omar', 'other', NULL, '대만', 45, NULL, '포트'),
('Amrut Fusion Single Malt Whisky', 'Amrut', 'other', NULL, '인도', 42.8, NULL, '버번/셰리'),
('Amrut Single Malt Whisky 10 Year', 'Amrut', 'other', NULL, '인도', 42.8, 10, '버번'),
('Amrut Port Wood Finish', 'Amrut', 'other', NULL, '인도', 42.8, NULL, '포트'),
('Amrut Peated Single Malt Whisky', 'Amrut', 'other', NULL, '인도', 42.8, NULL, '버번'),
('Amrut 18 Year Single Malt Whisky', 'Amrut', 'other', NULL, '인도', 46, 18, '버번'),
('Paul John Single Malt Whisky 10 Year', 'Paul John', 'other', NULL, '인도', 42.8, 10, '버번'),
('Paul John Edited (NAS) Single Malt Whisky', 'Paul John', 'other', NULL, '인도', 42.8, NULL, NULL),
('Paul John Peated Single Malt Whisky', 'Paul John', 'other', NULL, '인도', 42.8, NULL, '버번'),
('Paul John 12 Year Single Malt Whisky', 'Paul John', 'other', NULL, '인도', 42.8, 12, '버번'),
('Paul John Single Cask 2015', 'Paul John', 'other', NULL, '인도', 46, NULL, '버번'),
('Rampur Indian Single Malt Whisky 12 Year', 'Rampur', 'other', NULL, '인도', 42.8, 12, '버번'),
('Rampur Single Cask (NAS) Single Malt Whisky', 'Rampur', 'other', NULL, '인도', 42.8, NULL, NULL),
('Rampur 18 Year Single Malt Whisky', 'Rampur', 'other', NULL, '인도', 46, 18, '버번'),
('Rampur 25 Year Single Malt Whisky', 'Rampur', 'other', NULL, '인도', 46, 25, '버번'),
('Rampur 30 Year Single Malt Whisky', 'Rampur', 'other', NULL, '인도', 46, 30, '버번'),
('Indri Single Malt Whisky 12 Year', 'Indri', 'other', NULL, '인도', 42.8, 12, '버번'),
('Indri Peated Single Malt Whisky (NAS)', 'Indri', 'other', NULL, '인도', 42.8, NULL, '버번'),
('Indri 18 Year Single Malt Whisky', 'Indri', 'other', NULL, '인도', 46, 18, '버번'),
('Indri Single Cask (NAS) Single Malt Whisky', 'Indri', 'other', NULL, '인도', 42.8, NULL, NULL),
('Indri 25 Year Single Malt Whisky', 'Indri', 'other', NULL, '인도', 46, 25, '버번'),
('Starward Nova', 'Starward', 'other', NULL, NULL, 46, NULL, '버번'),
('Starward 10 Year', 'Starward', 'other', NULL, NULL, 46, 10, '버번'),
('Starward 12 Year', 'Starward', 'other', NULL, NULL, 46, 12, '버번'),
('Starward 15 Year', 'Starward', 'other', NULL, NULL, 46, 15, '버번'),
('Starward 18 Year', 'Starward', 'other', NULL, NULL, 46, 18, '버번'),
('Starward 30 Year', 'Starward', 'other', NULL, NULL, 46, 30, '버번'),
('Sullivans Cove French Oak', 'Sullivans Cove', 'other', NULL, NULL, 46, NULL, '프랑스 오크'),
('Sullivans Cove 12 Year', 'Sullivans Cove', 'other', NULL, NULL, 46, 12, '버번'),
('Sullivans Cove 15 Year', 'Sullivans Cove', 'other', NULL, NULL, 46, 15, '버번'),
('Sullivans Cove 18 Year', 'Sullivans Cove', 'other', NULL, NULL, 46, 18, '버번'),
('Sullivans Cove 21 Year', 'Sullivans Cove', 'other', NULL, NULL, 46, 21, '버번'),
('Sullivans Cove 30 Year', 'Sullivans Cove', 'other', NULL, NULL, 46, 30, '버번'),
('Penderyn Single Malt', 'Penderyn', 'other', NULL, NULL, 46, NULL, '버번'),
('Penderyn 10 Year', 'Penderyn', 'other', NULL, NULL, 46, 10, '버번'),
('Penderyn 12 Year', 'Penderyn', 'other', NULL, NULL, 46, 12, '버번'),
('Penderyn 15 Year', 'Penderyn', 'other', NULL, NULL, 46, 15, '버번'),
('Penderyn Peated', 'Penderyn', 'other', NULL, NULL, 46, NULL, '버번'),
('Penderyn Sherry Finish', 'Penderyn', 'other', NULL, NULL, 46, NULL, '셰리'),
('Cotswolds Single Malt', 'Cotswolds', 'other', NULL, NULL, 46, NULL, '버번'),
('Cotswolds 12 Year', 'Cotswolds', 'other', NULL, NULL, 46, 12, '버번'),
('Cotswolds 15 Year', 'Cotswolds', 'other', NULL, NULL, 46, 15, '버번'),
('Cotswolds 21 Year', 'Cotswolds', 'other', NULL, NULL, 46, 21, '버번'),
('Cotswolds 30 Year', 'Cotswolds', 'other', NULL, NULL, 46, 30, '버번'),
('Milk & Honey Single Malt', 'Milk & Honey', 'other', NULL, NULL, 46, NULL, '버번'),
('Milk & Honey 10 Year', 'Milk & Honey', 'other', NULL, NULL, 46, 10, '버번'),
('Milk & Honey 12 Year', 'Milk & Honey', 'other', NULL, NULL, 46, 12, '버번'),
('Milk & Honey 15 Year', 'Milk & Honey', 'other', NULL, NULL, 46, 15, '버번'),
('Milk & Honey 18 Year', 'Milk & Honey', 'other', NULL, NULL, 46, 18, '버번'),
('Milk & Honey 21 Year', 'Milk & Honey', 'other', NULL, NULL, 46, 21, '버번'),
('Mackmyra Svensk Ek', 'Mackmyra', 'other', NULL, NULL, 46, NULL, '버번'),
('Mackmyra 5 Year', 'Mackmyra', 'other', NULL, NULL, 46, 5, '버번'),
('Mackmyra 10 Year', 'Mackmyra', 'other', NULL, NULL, 46, 10, '버번'),
('Mackmyra 12 Year', 'Mackmyra', 'other', NULL, NULL, 46, 12, '버번'),
('Mackmyra 15 Year', 'Mackmyra', 'other', NULL, NULL, 46, 15, '버번'),
('Mackmyra 18 Year', 'Mackmyra', 'other', NULL, NULL, 46, 18, '버번'),
('Mackmyra 21 Year', 'Mackmyra', 'other', NULL, NULL, 46, 21, '버번'),
('Mackmyra 30 Year', 'Mackmyra', 'other', NULL, NULL, 46, 30, '버번'),
('Crown Royal', 'Crown Royal', 'other', NULL, '캐나다', 40, NULL, NULL),
('Crown Royal XR', 'Crown Royal', 'other', NULL, '캐나다', 40, 10, '오크'),
('Crown Royal Reserve', 'Crown Royal', 'other', NULL, '캐나다', 40, 12, '오크'),
('Canadian Club 100% Rye', 'Canadian Club', 'other', NULL, '캐나다', 40, NULL, NULL),
('Canadian Club 12 Year', 'Canadian Club', 'other', NULL, '캐나다', 40, 12, NULL),
('Canadian Club 30th Anniversary', 'Canadian Club', 'other', NULL, '캐나다', 40, NULL, NULL),
('Lot No. 40', 'Lot No. 40', 'other', NULL, '캐나다', 40, NULL, NULL),
('Lot No. 40 Rye', 'Lot No. 40', 'other', NULL, '캐나다', 45, NULL, NULL)
ON CONFLICT (name) DO NOTHING;

INSERT INTO whisky_note.catalog (name, distillery, category, region, country, abv, age_years, cask_type) VALUES
('Lot No. 40 12 Year', 'Lot No. 40', 'other', NULL, '캐나다', 45, 12, NULL)
ON CONFLICT (name) DO NOTHING;

